{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "## Full code/command that generated the error\r\n\r\nI executed all cells in http://try.gmtpython.xyz and the last one didn't output the desired result, instead it just output a blank background image.\r\n\r\nI also tried to run locally, but the result was the same, no globe output.\r\n\r\n## Full error message\r\n\r\nAny printed error.\r\n\r\n## System information\r\n\r\n* Operating system: Linux debian (9.3) 4.9.65-3+deb9u2\r\n* Python installation (Anaconda, system, ETS): conda 4.4.10\r\n* Version of GMT/Python: I don't know, commit 270880619. libgmt is 6.0.0, Python 3.6.4, jupyter-notebook 5.2.2\r\n* Browser: Firefox Quantum 58.0.1\r\n* How you installed GMT/Python: cloned repo, created conda env, make develop, set LD_LIBRARY_PATH\r\n\r\n__*mybinder*__\r\n![gmt-globe-online](https://user-images.githubusercontent.com/9625617/36511695-709d6824-1746-11e8-9cf1-2881a0209c9e.png)\r\n\r\n__*local*__\r\n![gmt-globe-local](https://user-images.githubusercontent.com/9625617/36511946-8cb32494-1747-11e8-86f8-b7a7b6cb8828.png)\r\n",
    "closed_at": "2018-02-22T03:16:04Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
        "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
        "followers_url": "https://api.github.com/users/leouieda/followers",
        "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
        "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/leouieda",
        "id": 290082,
        "login": "leouieda",
        "node_id": "MDQ6VXNlcjI5MDA4Mg==",
        "organizations_url": "https://api.github.com/users/leouieda/orgs",
        "received_events_url": "https://api.github.com/users/leouieda/received_events",
        "repos_url": "https://api.github.com/users/leouieda/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/leouieda"
    },
    "comments": 4,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "Thanks, Rafael. I can confirm the bug on my own machine with Firefox 58.0.2. Don't what happened because it was working yesterday with the exact same specs. It might have been something in WorldWind that changed. I'll investigate further. ",
            "created_at": "2018-02-22T00:07:27Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/134#issuecomment-367521685",
            "id": 367521685,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2NzUyMTY4NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367521685/reactions"
            },
            "updated_at": "2018-02-22T00:07:27Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367521685",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@rafaelmds do you have the proprietary nvidia drivers installed on your system?",
            "created_at": "2018-02-22T00:18:31Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/134#issuecomment-367523760",
            "id": 367523760,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2NzUyMzc2MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367523760/reactions"
            },
            "updated_at": "2018-02-22T00:18:31Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367523760",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "The laptop has a nvidia optimus.\r\n\r\nI'm using i915 for the Intel and bumblebee with nvidia proprietary driver.\r\n\r\nI can confirm it **is working** using optirun (to use nvidia proprietary driver) to launch jupyter notebook and firefox.",
            "created_at": "2018-02-22T01:18:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/134#issuecomment-367534955",
            "id": 367534955,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2NzUzNDk1NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367534955/reactions"
            },
            "updated_at": "2018-02-22T01:18:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367534955",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9625617?v=4",
                "events_url": "https://api.github.com/users/rafaelmds/events{/privacy}",
                "followers_url": "https://api.github.com/users/rafaelmds/followers",
                "following_url": "https://api.github.com/users/rafaelmds/following{/other_user}",
                "gists_url": "https://api.github.com/users/rafaelmds/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/rafaelmds",
                "id": 9625617,
                "login": "rafaelmds",
                "node_id": "MDQ6VXNlcjk2MjU2MTc=",
                "organizations_url": "https://api.github.com/users/rafaelmds/orgs",
                "received_events_url": "https://api.github.com/users/rafaelmds/received_events",
                "repos_url": "https://api.github.com/users/rafaelmds/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/rafaelmds/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rafaelmds/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/rafaelmds"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Yep, it's a graphics card problem for the webgl rendering. I had upgrade my driver yesterday and that was what broke it for me. Managed to get it working again with the proprietary nvidia driver on my desktop.\r\n\r\nOK, so it seems like it's not really a bug. I don't imagine many people will run into this issue using bumblebee. \r\n\r\nThanks for opening the issue and trying it out!",
            "created_at": "2018-02-22T03:16:01Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/134#issuecomment-367554373",
            "id": 367554373,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2NzU1NDM3Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367554373/reactions"
            },
            "updated_at": "2018-02-22T03:16:01Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/367554373",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134/comments",
    "created_at": "2018-02-21T23:43:56Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/134",
    "id": 299171495,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUyOTkxNzE0OTU=",
    "number": 134,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134/timeline",
    "title": "Interactive globe in the Jupyter notebook not working in Firefox Quantum 58.0.1",
    "updated_at": "2018-02-22T03:16:04Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/134",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/9625617?v=4",
        "events_url": "https://api.github.com/users/rafaelmds/events{/privacy}",
        "followers_url": "https://api.github.com/users/rafaelmds/followers",
        "following_url": "https://api.github.com/users/rafaelmds/following{/other_user}",
        "gists_url": "https://api.github.com/users/rafaelmds/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/rafaelmds",
        "id": 9625617,
        "login": "rafaelmds",
        "node_id": "MDQ6VXNlcjk2MjU2MTc=",
        "organizations_url": "https://api.github.com/users/rafaelmds/orgs",
        "received_events_url": "https://api.github.com/users/rafaelmds/received_events",
        "repos_url": "https://api.github.com/users/rafaelmds/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/rafaelmds/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rafaelmds/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/rafaelmds"
    }
}