{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\nI'm trying to plot two vectors using the following script. It works well if pen is set to `1p,black` (i.e. a simple line), but crashes if set to `1p,black+ve0.2c`. Actually, the first **plot** works, but the second one crashes.\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\nimport numpy as np\r\n\r\nfig = pygmt.Figure()\r\nfig.basemap(projection=\"X15c/10c\", region=\"400/600/5/8\", frame=True)\r\nfig.plot(x=[530.0, 530.0], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.plot(x=[570.0, 570.0], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.savefig(\"map.pdf\")\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\npython(64354,0x11ac3bdc0) malloc: *** error for object 0x7f8f28e50900: pointer being freed was not allocated\r\npython(64354,0x11ac3bdc0) malloc: *** set a breakpoint in malloc_error_break to debug\r\n[1]    64354 abort      python test.py\r\n```\r\n\r\n**System information**\r\n\r\n* Operating system: macOS\r\n* Python installation (Anaconda, system, ETS): Anaconda\r\n* Version of GMT:  6.1.0_e6eb3b9_2020.03.30\r\n* Version of Python: 3.7.4\r\n* Version of this package: 0.0.1a0+75.g088b0d1\r\n* If using conda, paste the output of `conda list` below:\r\n\r\n<details>\r\n<summary>output of conda list</summary>\r\n<pre>\r\nPASTE OUTPUT OF CONDA LIST HERE\r\n</pre>\r\n</details>\r\n",
    "closed_at": "2020-06-24T04:40:13Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 3,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "I can reproduce the same crash, with GMT 6.0 on Linux and using the pygmt master branch. The corresponding code in GMT works though:\r\n\r\n```bash\r\ngmt begin test png\r\ngmt basemap -JX15c/10c -R400/600/5/8 -B\r\ngmt plot -W1p,black+ve0.2c << EOF\r\n530.0 6.0\r\n530.0 7.0\r\nEOF\r\ngmt plot -W1p,black+ve0.2c << EOF\r\n570.0 6.0\r\n570.0 7.0\r\nEOF\r\ngmt end show\r\n```\r\nproduces:\r\n\r\n![two vertical lines plotted successfully using gmt](https://user-images.githubusercontent.com/23487320/78000607-0637e500-7391-11ea-8ecf-9a92ab903338.png)\r\n\r\nNot much of a clue as to why it's crashing though :man_shrugging:",
            "created_at": "2020-03-31T07:52:11Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/406#issuecomment-606461712",
            "id": 606461712,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYwNjQ2MTcxMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/606461712/reactions"
            },
            "updated_at": "2020-03-31T07:52:11Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/606461712",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "Also crushes on the second plot, but\r\ndoes not crush if integer values are used.\r\nThat is\r\n```python\r\nimport pygmt\r\nimport numpy as np\r\n\r\nfig = pygmt.Figure()\r\nfig.basemap(projection=\"X15c/10c\", region=\"400/600/5/8\", frame=True)\r\nfig.plot(x=[530, 530], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.plot(x=[570, 570], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.savefig(\"map.pdf\")\r\n```\r\nworks fine\r\n\r\n```python\r\nfig.plot(x=[530, 530], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.plot(x=[570.0, 570.0], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\n```\r\nalso works fine\r\n\r\n```python\r\nfig.plot(x=[530.0, 530.0], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.plot(x=[570, 570], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\n```\r\ndoes not work\r\n\r\nSeems like the issue is related to floating point numbers,\r\nalso the data for later plots is converted to the data type of the first plot.",
            "created_at": "2020-05-08T09:37:33Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/406#issuecomment-625732121",
            "id": 625732121,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyNTczMjEyMQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/625732121/reactions"
            },
            "updated_at": "2020-05-08T09:37:33Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/625732121",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7131929?v=4",
                "events_url": "https://api.github.com/users/d-murashkin/events{/privacy}",
                "followers_url": "https://api.github.com/users/d-murashkin/followers",
                "following_url": "https://api.github.com/users/d-murashkin/following{/other_user}",
                "gists_url": "https://api.github.com/users/d-murashkin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/d-murashkin",
                "id": 7131929,
                "login": "d-murashkin",
                "node_id": "MDQ6VXNlcjcxMzE5Mjk=",
                "organizations_url": "https://api.github.com/users/d-murashkin/orgs",
                "received_events_url": "https://api.github.com/users/d-murashkin/received_events",
                "repos_url": "https://api.github.com/users/d-murashkin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/d-murashkin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/d-murashkin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/d-murashkin"
            }
        },
        {
            "author_association": "NONE",
            "body": "I might have found a solution:\r\nconvert all floating point numbers to float32 (float64 is default)\r\nThe following works with no error:\r\n```python\r\nimport pygmt\r\nimport numpy as np\r\n\r\nfig = pygmt.Figure()\r\nfig.basemap(projection=\"X15c/10c\", region=\"400/600/5/8\", frame=True)\r\nfig.plot(x=[np.float32(530.0), np.float32(530.0)], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.plot(x=[np.float32(570.0), np.float32(570.0)], y=[6.0, 7.0], pen='1p,black+ve0.2c')\r\nfig.savefig(\"map.pdf\")\r\n```\r\nCould it be that GMT does not have good support for float64 and uses float32 by default?\r\nAnyway, for plotting float64 values are probably not needed, so all float64 data should probably converted to float32 in the wrapper.",
            "created_at": "2020-05-08T10:16:22Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/406#issuecomment-625746279",
            "id": 625746279,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyNTc0NjI3OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/625746279/reactions"
            },
            "updated_at": "2020-05-08T10:16:22Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/625746279",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7131929?v=4",
                "events_url": "https://api.github.com/users/d-murashkin/events{/privacy}",
                "followers_url": "https://api.github.com/users/d-murashkin/followers",
                "following_url": "https://api.github.com/users/d-murashkin/following{/other_user}",
                "gists_url": "https://api.github.com/users/d-murashkin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/d-murashkin",
                "id": 7131929,
                "login": "d-murashkin",
                "node_id": "MDQ6VXNlcjcxMzE5Mjk=",
                "organizations_url": "https://api.github.com/users/d-murashkin/orgs",
                "received_events_url": "https://api.github.com/users/d-murashkin/received_events",
                "repos_url": "https://api.github.com/users/d-murashkin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/d-murashkin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/d-murashkin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/d-murashkin"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406/comments",
    "created_at": "2020-03-30T21:19:17Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/406",
    "id": 590603370,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU1OTA2MDMzNzA=",
    "number": 406,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406/timeline",
    "title": "plot crashes when plotting arrows ",
    "updated_at": "2020-06-24T04:40:13Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/406",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    }
}