{
    "active_lock_reason": null,
    "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
        "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
        "followers_url": "https://api.github.com/users/maxrjones/followers",
        "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
        "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/maxrjones",
        "id": 14077947,
        "login": "maxrjones",
        "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
        "organizations_url": "https://api.github.com/users/maxrjones/orgs",
        "received_events_url": "https://api.github.com/users/maxrjones/received_events",
        "repos_url": "https://api.github.com/users/maxrjones/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/maxrjones"
    },
    "assignees": [
        {
            "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
            "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
            "followers_url": "https://api.github.com/users/maxrjones/followers",
            "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
            "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/maxrjones",
            "id": 14077947,
            "login": "maxrjones",
            "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
            "organizations_url": "https://api.github.com/users/maxrjones/orgs",
            "received_events_url": "https://api.github.com/users/maxrjones/received_events",
            "repos_url": "https://api.github.com/users/maxrjones/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/maxrjones"
        }
    ],
    "author_association": "CONTRIBUTOR",
    "body": "**Description of the problem**\r\n\r\nI am getting the following error while dealing with plotting time-series(dates as x-axis):\r\npython(34471,0x1169cd5c0) malloc: *** error for object 0x7fcd964cf330: pointer being freed was not allocated\r\npython(34471,0x1169cd5c0) malloc: *** set a breakpoint in malloc_error_break to debug\r\nI am not sure it may be an upstream GMT issue\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport numpy as np\r\nimport pandas as pd\r\nimport pygmt as gmt\r\n\r\nt = pd.date_range(pd.to_datetime('03-13-2021'), pd.to_datetime('04-10-2021'))\r\n\r\nfig = gmt.Figure()\r\ngmt.config(FORMAT_DATE_MAP='dd-mm')\r\nfig.basemap(\r\n    projection='X10/5',\r\n    region=[t[0], t[-1], -0.1, 30],\r\n    frame=True\r\n)\r\nfig.plot(\r\n    x=t,\r\n    y=np.ones(t.shape[0])\r\n)\r\nfig.show()\r\n```\r\n\r\nthe script above works when changing the `fig.plot` to be:\r\n```python\r\nfig.plot(\r\n    x=t,\r\n    y=np.arange(t.shape[0])\r\n)\r\n``` \r\nbut fails with `np.zeros`, `np.random.rand`, and my real-world data.\r\n\r\n**Full error message**\r\n\r\n```\r\npython(35111,0x10ef505c0) malloc: *** error for object 0x7fb538cc7ec0: pointer being freed was not allocated\r\npython(35111,0x10ef505c0) malloc: *** set a breakpoint in malloc_error_break to debug\r\nAbort trap: 6\r\n```\r\n\r\n**System information**\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.5.0\r\nSystem information:\r\n  python: 3.10.1 | packaged by conda-forge | (main, Dec 16 2021, 18:00:56) [Clang 11.1.0 ]\r\n  executable: /Users/yohai/anaconda3/envs/ibaraki_proj/bin/python\r\n  machine: macOS-10.14.6-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.21.4\r\n  pandas: 1.3.5\r\n  xarray: 0.20.2\r\n  netCDF4: 1.5.8\r\n  packaging: 21.3\r\n  ghostscript: 9.50\r\n  gmt: 6.1.0\r\nGMT library information:\r\n  binary dir: /Users/yohai/anaconda3/envs/ibaraki_proj/bin\r\n  cores: 12\r\n  grid layout: rows\r\n  library path: /Users/yohai/anaconda3/envs/ibaraki_proj/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /Users/yohai/anaconda3/envs/ibaraki_proj/lib/gmt/plugins\r\n  share dir: /Users/yohai/anaconda3/envs/ibaraki_proj/share/gmt\r\n  version: 6.3.0\r\n```\r\n",
    "closed_at": "2022-04-05T15:42:28Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
        "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
        "followers_url": "https://api.github.com/users/maxrjones/followers",
        "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
        "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/maxrjones",
        "id": 14077947,
        "login": "maxrjones",
        "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
        "organizations_url": "https://api.github.com/users/maxrjones/orgs",
        "received_events_url": "https://api.github.com/users/maxrjones/received_events",
        "repos_url": "https://api.github.com/users/maxrjones/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/maxrjones"
    },
    "comments": 14,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "Thanks for the issue report - we should raise an error for this case. You need to specify the symbol parameters when using plot if they are not provided as part of your data:\r\n```\r\nimport numpy as np\r\nimport pandas as pd\r\nimport pygmt as gmt\r\n\r\nt = pd.date_range(pd.to_datetime('03-13-2021'), pd.to_datetime('04-10-2021'))\r\n\r\nfig = gmt.Figure()\r\ngmt.config(FORMAT_DATE_MAP='dd-mm')\r\nfig.basemap(\r\n    projection='X10/5',\r\n    region=[t[0], t[-1], -0.1, 30],\r\n    frame=True\r\n)\r\nfig.plot(\r\n    x=t,\r\n    y=np.ones(t.shape[0]),\r\n    style=\"c0.4c\",\r\n    pen=\"1p\",\r\n    color=\"red3\"\r\n)\r\nfig.show()\r\n```",
            "created_at": "2022-01-03T17:19:40Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1004237877",
            "id": 1004237877,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO84723Q1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1004237877/reactions"
            },
            "updated_at": "2022-01-03T17:19:40Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1004237877",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> You need to specify the symbol parameters when using plot if they are not provided as part of your data:\r\n\r\nIf the symbol parameter `style` is not given, it means users want to plot a line. So the script from @yohaimagen should work. Am I misunderstand anything?",
            "created_at": "2022-01-04T05:06:47Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1004531929",
            "id": 1004531929,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO8473_DZ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1004531929/reactions"
            },
            "updated_at": "2022-01-04T05:06:47Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1004531929",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "That is what I thought, I attended to plot a line.",
            "created_at": "2022-01-04T06:36:46Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1004560778",
            "id": 1004560778,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO8474GGK",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1004560778/reactions"
            },
            "updated_at": "2022-01-04T06:36:46Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1004560778",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/12828255?v=4",
                "events_url": "https://api.github.com/users/yohaimagen/events{/privacy}",
                "followers_url": "https://api.github.com/users/yohaimagen/followers",
                "following_url": "https://api.github.com/users/yohaimagen/following{/other_user}",
                "gists_url": "https://api.github.com/users/yohaimagen/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/yohaimagen",
                "id": 12828255,
                "login": "yohaimagen",
                "node_id": "MDQ6VXNlcjEyODI4MjU1",
                "organizations_url": "https://api.github.com/users/yohaimagen/orgs",
                "received_events_url": "https://api.github.com/users/yohaimagen/received_events",
                "repos_url": "https://api.github.com/users/yohaimagen/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/yohaimagen/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/yohaimagen/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/yohaimagen"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Thanks for the clarification, I'll work on debugging the issue.",
            "created_at": "2022-01-04T23:34:06Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1005250112",
            "id": 1005250112,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO8476uZA",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1005250112/reactions"
            },
            "updated_at": "2022-01-04T23:34:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1005250112",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This looks like an upstream bug. Here is a smaller script to reproduce the issue:\r\n```\r\nimport pygmt\r\n\r\nfig = pygmt.Figure()\r\nfig.plot(\r\n    projection='X10/5',\r\n    region=\"2021-03-01/2021-03-04/-0.1/30\",\r\n    frame=True,\r\n    x=[\"2021-03-01\", \"2021-03-02\", \"2021-03-03\", \"2021-03-04\"],\r\n    y=[0., 1., 2., 3.],\r\n    #y=[0, 1, 2, 3],\r\n)\r\nfig.savefig(\"map.png\", show=True)\r\n```\r\n`y=[0., 1., 2., 3.]` crashes but `y=[0, 1, 2, 3]` works.\r\n\r\nPing @meghanrjones or @PaulWessel to see if you have time debugging it.",
            "created_at": "2022-03-05T06:13:22Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1059703562",
            "id": 1059703562,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO84_KcsK",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1059703562/reactions"
            },
            "updated_at": "2022-03-05T06:13:22Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1059703562",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'll try again to debug tomorrow. I ran into a wall last time, if that happens again I will at least post what I find.",
            "created_at": "2022-03-06T13:37:14Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1059964337",
            "id": 1059964337,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO84_LcWx",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1059964337/reactions"
            },
            "updated_at": "2022-03-06T13:37:14Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1059964337",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "GMT changes the method from GMT_IN|GMT_IS_REFERENCE to GMT_IN|GMT_IS_DUPLICATE for any cases with non-double data (see https://github.com/GenericMappingTools/gmt/blob/a8bbbcf59ef6d4d20a456278f52605328df046a6/src/gmt_api.c#L9020-L9022). The data are duplicated for `y=[0, 1, 2, 3]`, but not for `y=[0., 1., 2., 3.]`, which is why one crashes but not the other.\r\n\r\nSo, there is a problem with passing GMT_DATASET structures via GMT_IS_REFERENCE. I found that this crash started after https://github.com/GenericMappingTools/gmt/pull/5953 was merged. @PaulWessel, would you be able to take another look at the memory management for this case?\r\n\r\nHere is the simple example that fails for this case:\r\n```\r\nimport pygmt\r\n\r\nfig = pygmt.Figure()\r\nfig.plot(\r\n    projection='X10/5',\r\n    region=\"2021-03-01/2021-03-04/-0.1/30\",\r\n    frame=True,\r\n    x=[\"2021-03-01\", \"2021-03-02\", \"2021-03-03\", \"2021-03-04\"],\r\n    y=[0., 1., 2., 3.],\r\n    #y=[0, 1, 2, 3],\r\n)\r\n```\r\n",
            "created_at": "2022-04-01T22:15:28Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1086377722",
            "id": 1086377722,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85AwM76",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086377722/reactions"
            },
            "updated_at": "2022-04-02T13:08:36Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086377722",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I would love to debug this one but apparently the conda stuff is still Intel only, which makes it pretty hard to debug on M1. But if you can do this you should be able to determine what is the difference between the two cases.   I dont understand my a double array gets duplicated (double is the natural type of datasets). A re you sure it is not the integer array that requires duplication - surely it does?",
            "created_at": "2022-04-02T11:48:43Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1086622818",
            "id": 1086622818,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85AxIxi",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086622818/reactions"
            },
            "updated_at": "2022-04-02T11:48:43Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086622818",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I would love to debug this one but apparently the conda stuff is still Intel only, which makes it pretty hard to debug on M1. But if you can do this you should be able to determine what is the difference between the two cases. I dont understand my a double array gets duplicated (double is the natural type of datasets). A re you sure it is not the integer array that requires duplication - surely it does?\r\n\r\nsorry, copy-paste error when making the comment. Yes, double arrays are referenced (and crash). int arrays are duplicated (without issue).",
            "created_at": "2022-04-02T13:08:19Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1086637241",
            "id": 1086637241,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85AxMS5",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086637241/reactions"
            },
            "updated_at": "2022-04-02T13:08:19Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086637241",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I would love to debug this one but apparently the conda stuff is still Intel only, which makes it pretty hard to debug on M1.\r\n\r\nWhat exactly did you mean? Installing GMT from conda works well on my M1.",
            "created_at": "2022-04-02T13:58:30Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1086646802",
            "id": 1086646802,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85AxOoS",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086646802/reactions"
            },
            "updated_at": "2022-04-02T13:58:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086646802",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "My experience has been that my conda installation (I have used miniconda but same with conda) the binaries are all Intel and things run under Rosetta2.  Thus, when I try to debug I get failures due to mixed architectures....\r\nAre you able to actually follow the PyGMT debug guidelines on our site and set stop points in Xcode and it works on M1?",
            "created_at": "2022-04-02T14:03:26Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1086647711",
            "id": 1086647711,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85AxO2f",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086647711/reactions"
            },
            "updated_at": "2022-04-02T14:03:26Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086647711",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I haven't tried to debug PyGMT in Xcode on M1.",
            "created_at": "2022-04-02T14:15:25Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1086649844",
            "id": 1086649844,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85AxPX0",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086649844/reactions"
            },
            "updated_at": "2022-04-02T14:15:44Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1086649844",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This was fixed by https://github.com/GenericMappingTools/gmt/pull/6521. I added a C API test so I don't think we need another regression test in the PyGMT repository.",
            "created_at": "2022-04-05T15:42:27Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1088891175",
            "id": 1088891175,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85A5ykn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1088891175/reactions"
            },
            "updated_at": "2022-04-05T15:42:27Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1088891175",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I've triggered a GMT dev version bump at https://github.com/conda-forge/gmt-feedstock/pull/203, so once that's merged in a few hours (and assuming you don't mind using an unstable GMT version), you can either:\r\n\r\n1. Run `conda install -c conda-forge/label/dev gmt=6.4.0`\r\n2. Build GMT from source (see https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md) and set `GMT_LIBRARY_PATH` to the correct folder following https://www.pygmt.org/dev/install.html#finding-the-gmt-shared-library.\r\n\r\nEither method should give you the latest patched version of GMT. Let us know if it works or if you need any additional clarification.",
            "created_at": "2022-04-05T16:01:16Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691#issuecomment-1088927951",
            "id": 1088927951,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
            "node_id": "IC_kwDOBRZfO85A57jP",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1088927951/reactions"
            },
            "updated_at": "2022-04-05T16:01:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1088927951",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691/comments",
    "created_at": "2022-01-02T07:38:43Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1691",
    "id": 1091967616,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 164,
        "created_at": "2022-06-12T13:10:39Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": "2022-11-01T07:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/14",
        "id": 8073518,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/14/labels",
        "node_id": "MI_kwDOBRZfO84AezEu",
        "number": 14,
        "open_issues": 62,
        "state": "open",
        "title": "0.8.0",
        "updated_at": "2022-11-07T11:23:55Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/14"
    },
    "node_id": "I_kwDOBRZfO85BFhqA",
    "number": 1691,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691/timeline",
    "title": "getting malloc error while dealing with dates.",
    "updated_at": "2022-07-05T14:06:37Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1691",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/12828255?v=4",
        "events_url": "https://api.github.com/users/yohaimagen/events{/privacy}",
        "followers_url": "https://api.github.com/users/yohaimagen/followers",
        "following_url": "https://api.github.com/users/yohaimagen/following{/other_user}",
        "gists_url": "https://api.github.com/users/yohaimagen/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/yohaimagen",
        "id": 12828255,
        "login": "yohaimagen",
        "node_id": "MDQ6VXNlcjEyODI4MjU1",
        "organizations_url": "https://api.github.com/users/yohaimagen/orgs",
        "received_events_url": "https://api.github.com/users/yohaimagen/received_events",
        "repos_url": "https://api.github.com/users/yohaimagen/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/yohaimagen/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/yohaimagen/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/yohaimagen"
    }
}