{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "**Description of the problem**\r\nI recently updated to pygmt v0.5.0 (cloned my v.0.4.0 environment then ran: conda update pygmt) and now I'm having an issue with pygmt.plot when trying to plot shapefiles. Below is an example of a script which works fine in my v.0.4.0 env but produces the below error with v0.5.0. \r\n\r\nThis error happens with any shapefiles I've tried. Here's a link to this specific one: https://doi.pangaea.de/10.1594/PANGAEA.819147\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\n\r\nfigheight=180 # in mm\r\n\r\n# for Ross Ice Shelf\r\nris_xl=-660_000\r\nris_yl=-1_500_000\r\nris_xh=470_000\r\nris_yh=-400_000\r\n\r\n# Calculate the figure width and map scale\r\nfigwidth=figheight*(ris_xh-ris_xl)/(ris_yh-ris_yl)\r\nrisratio = (ris_yh - ris_yl) / (figheight/1000)\r\n# Make a GMT region string and projection strings in both PS71 and Lon/Lat\r\nrisreg = str(ris_xl) + '/' + str(ris_xh) + '/' + str(ris_yl) + '/' + str(ris_yh) #W/E/S/N\r\nrisproj = \"x1:\" + str(risratio)\r\nrisproj_ll = \"s0/-90/-71/1:\" + str(risratio)\r\n\r\nfig = pygmt.Figure()\r\n\r\n# Plot Shapefiles\r\nfig.plot(data='../PyGMT/Venturelli2020/scripps_antarctica_polygons_v1.shp', region = risreg, projection = risproj, pen = '0.5p,black')\r\n\r\nfig.show()\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\n---------------------------------------------------------------------------\r\nUnicodeDecodeError                        Traceback (most recent call last)\r\n<ipython-input-8-1bd9f90ba3c5> in <module>\r\n     20 \r\n     21 # Plot Shapefiles\r\n---> 22 fig.plot(data='../PyGMT/Venturelli2020/scripps_antarctica_polygons_v1.shp', region = risreg, projection = risproj, pen = '0.5p,black')\r\n     23 \r\n     24 fig.show()\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\site-packages\\pygmt\\helpers\\decorators.py in new_module(*args, **kwargs)\r\n    803                 warnings.warn(msg, category=FutureWarning, stacklevel=2)\r\n    804                 kwargs[newname] = kwargs.pop(oldname)\r\n--> 805             return module_func(*args, **kwargs)\r\n    806 \r\n    807         return new_module\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\site-packages\\pygmt\\helpers\\decorators.py in new_module(*args, **kwargs)\r\n    803                 warnings.warn(msg, category=FutureWarning, stacklevel=2)\r\n    804                 kwargs[newname] = kwargs.pop(oldname)\r\n--> 805             return module_func(*args, **kwargs)\r\n    806 \r\n    807         return new_module\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\site-packages\\pygmt\\helpers\\decorators.py in new_module(*args, **kwargs)\r\n    871                 )\r\n    872                 warnings.warn(msg, category=FutureWarning, stacklevel=2)\r\n--> 873             return module_func(*args, **kwargs)\r\n    874 \r\n    875         return new_module\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\site-packages\\pygmt\\helpers\\decorators.py in new_module(*args, **kwargs)\r\n    584                     )\r\n    585                     warnings.warn(msg, category=SyntaxWarning, stacklevel=2)\r\n--> 586             return module_func(*args, **kwargs)\r\n    587 \r\n    588         new_module.aliases = aliases\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\site-packages\\pygmt\\helpers\\decorators.py in new_module(*args, **kwargs)\r\n    724                         kwargs[arg] = separators[fmt].join(f\"{item}\" for item in value)\r\n    725             # Execute the original function and return its output\r\n--> 726             return module_func(*args, **kwargs)\r\n    727 \r\n    728         return new_module\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\site-packages\\pygmt\\src\\plot.py in plot(self, data, x, y, size, direction, **kwargs)\r\n    235         try:\r\n    236             with open(which(data), mode=\"r\", encoding=\"utf8\") as file:\r\n--> 237                 line = file.readline()\r\n    238             if (\r\n    239                 \"@GMULTIPOINT\" in line or \"@GPOINT\" in line\r\n\r\n~\\Anaconda3\\envs\\pygmt05\\lib\\codecs.py in decode(self, input, final)\r\n    320         # decode input (taking the buffer into account)\r\n    321         data = self.buffer + input\r\n--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)\r\n    323         # keep undecoded input until the next call\r\n    324         self.buffer = data[consumed:]\r\n\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 26: invalid start byte\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.5.0\r\nSystem information:\r\n  python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]\r\n  executable: C:\\Users\\matthewt\\Anaconda3\\envs\\pygmt05\\python.exe\r\n  machine: Windows-10-10.0.17134-SP0\r\nDependency information:\r\n  numpy: 1.20.3\r\n  pandas: 1.2.4\r\n  xarray: 0.18.2\r\n  netCDF4: 1.5.7\r\n  packaging: 20.9\r\n  ghostscript: 9.54.0\r\n  gmt: 6.2.0\r\nGMT library information:\r\n  binary dir: C:/Users/matthewt/Anaconda3/envs/pygmt05\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: C:/Users/matthewt/Anaconda3/envs/pygmt05/Library/bin/gmt.dll\r\n  padding: 2\r\n  plugin dir: C:/Users/matthewt/Anaconda3/envs/pygmt05/Library/bin/gmt_plugins\r\n  share dir: C:/Users/matthewt/Anaconda3/envs/pygmt05/Library/share/gmt\r\n  version: 6.2.0\r\n```\r\n",
    "closed_at": "2022-03-01T01:31:04Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 7,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/main/CODE_OF_CONDUCT.md).\n",
            "created_at": "2021-11-07T23:21:07Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-962700712",
            "id": 962700712,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845YaWo",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962700712/reactions"
            },
            "updated_at": "2021-11-07T23:21:07Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962700712",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "A workaround is to load the shapefile with geopandas and plot the geodataframe, thanks to @weiji14 ",
            "created_at": "2021-11-07T23:27:05Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-962701773",
            "id": 962701773,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845YanN",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962701773/reactions"
            },
            "updated_at": "2021-11-07T23:27:05Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962701773",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/81199856?v=4",
                "events_url": "https://api.github.com/users/mdtanker/events{/privacy}",
                "followers_url": "https://api.github.com/users/mdtanker/followers",
                "following_url": "https://api.github.com/users/mdtanker/following{/other_user}",
                "gists_url": "https://api.github.com/users/mdtanker/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mdtanker",
                "id": 81199856,
                "login": "mdtanker",
                "node_id": "MDQ6VXNlcjgxMTk5ODU2",
                "organizations_url": "https://api.github.com/users/mdtanker/orgs",
                "received_events_url": "https://api.github.com/users/mdtanker/received_events",
                "repos_url": "https://api.github.com/users/mdtanker/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mdtanker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mdtanker/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mdtanker"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The utf8 decode bug was introduced at https://github.com/GenericMappingTools/pygmt/commit/0881d0feb7a3cd6657310d59f063c196dc86bcce#diff-20f52ad15c87b542274352e34c1520aa1c9376e2bab7148df2a6e9f479c6e1c9R222, might be a Windows specific issue.\r\n\r\n@mdtanker, another workaround is to explicitly set the `style`/`-S` parameter to bypass that check in the if-then block. I.e. use something like `fig.plot(data=\"file.shp\", style=\"c0.2c\", ...)`.",
            "created_at": "2021-11-07T23:40:39Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-962703815",
            "id": 962703815,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845YbHH",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962703815/reactions"
            },
            "updated_at": "2021-11-07T23:40:39Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962703815",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> might be a Windows specific issue.\r\n\r\nI think it's because the `.shp` file is not an plaintext file, so it makes no sense to open it using `mode=\"r\"`. It happens on macOS, too.",
            "created_at": "2021-11-08T02:20:53Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-962754928",
            "id": 962754928,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845Ynlw",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962754928/reactions"
            },
            "updated_at": "2021-11-08T02:20:53Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962754928",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> > might be a Windows specific issue.\r\n> \r\n> I think it's because the `.shp` file is not an plaintext file, so it makes no sense to open it using `mode=\"r\"`. It happens on macOS, too.\r\n\r\nAh you're right. I thought we set a condition that only files which end in `.gmt` have the default styling, but clearly not. So need to add an extra check that `datafile.endswith(\".gmt\")` or something.",
            "created_at": "2021-11-08T02:37:19Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-962760880",
            "id": 962760880,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845YpCw",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962760880/reactions"
            },
            "updated_at": "2021-11-08T02:37:19Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/962760880",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@GenericMappingTools/pygmt-maintainers, do you think this bug is critical enough to warrant a PyGMT v0.5.1 release? My feeling is that plotting a shapefile via `fig.plot(data=\"file.shp\", ...)` is something that is quite common (even though we don't advertise it much). There's also a few documentation related things (e.g. the tutorial reorganization, Liam's ROSES 2021 video, etc) that shouldn't take too long to get in by next week.\r\n\r\nOf course, there is a workaround for this, and the team might have other priorities (e.g. GMT 6.3), so maybe we can vote :+1: to do a PyGMT v0.5.1, and :-1: to just jump straight to PyGMT v0.6.0 for December/January. Will decide by end of the weekday 12 Nov (UTC time).",
            "created_at": "2021-11-09T22:22:03Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-964599434",
            "id": 964599434,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845fp6K",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 1,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/964599434/reactions"
            },
            "updated_at": "2021-11-09T22:22:57Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/964599434",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "> @GenericMappingTools/pygmt-maintainers, do you think this bug is critical enough to warrant a PyGMT v0.5.1 release? My feeling is that plotting a shapefile via `fig.plot(data=\"file.shp\", ...)` is something that is quite common (even though we don't advertise it much). There's also a few documentation related things (e.g. the tutorial reorganization, Liam's ROSES 2021 video, etc) that shouldn't take too long to get in by next week.\r\n> \r\n> Of course, there is a workaround for this, and the team might have other priorities (e.g. GMT 6.3), so maybe we can vote +1 to do a PyGMT v0.5.1, and -1 to just jump straight to PyGMT v0.6.0 for December/January. Will decide by end of the weekday 12 Nov (UTC time).\r\n\r\nI don't have any experience working with shapefiles, but I think two releases (or three, to include the contributors who work on GMT as well)  in the coming months is a lot to ask with it being the holiday season for the contributors in North America and Europe. Since there is a workaround using `geopandas`, I don't think it is that pressing for the functionality to be added in the next week or two instead of the coming months.",
            "created_at": "2021-11-10T10:47:16Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616#issuecomment-965009503",
            "id": 965009503,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
            "node_id": "IC_kwDOBRZfO845hOBf",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/965009503/reactions"
            },
            "updated_at": "2021-11-10T10:47:16Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/965009503",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29518865?v=4",
                "events_url": "https://api.github.com/users/willschlitzer/events{/privacy}",
                "followers_url": "https://api.github.com/users/willschlitzer/followers",
                "following_url": "https://api.github.com/users/willschlitzer/following{/other_user}",
                "gists_url": "https://api.github.com/users/willschlitzer/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/willschlitzer",
                "id": 29518865,
                "login": "willschlitzer",
                "node_id": "MDQ6VXNlcjI5NTE4ODY1",
                "organizations_url": "https://api.github.com/users/willschlitzer/orgs",
                "received_events_url": "https://api.github.com/users/willschlitzer/received_events",
                "repos_url": "https://api.github.com/users/willschlitzer/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/willschlitzer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/willschlitzer/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/willschlitzer"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616/comments",
    "created_at": "2021-11-07T23:21:05Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1616",
    "id": 1046877864,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2022-03-15T23:17:52Z",
        "closed_issues": 174,
        "created_at": "2021-06-23T03:22:20Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/9",
        "id": 6880166,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/9/labels",
        "node_id": "MDk6TWlsZXN0b25lNjg4MDE2Ng==",
        "number": 9,
        "open_issues": 0,
        "state": "closed",
        "title": "0.6.0",
        "updated_at": "2022-03-15T23:17:52Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/9"
    },
    "node_id": "I_kwDOBRZfO84-Zhao",
    "number": 1616,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616/timeline",
    "title": "pygmt v0.5.0 UnicodeDecodeError with fig.plot() when plotting shapefiles",
    "updated_at": "2022-03-01T01:31:04Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1616",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/81199856?v=4",
        "events_url": "https://api.github.com/users/mdtanker/events{/privacy}",
        "followers_url": "https://api.github.com/users/mdtanker/followers",
        "following_url": "https://api.github.com/users/mdtanker/following{/other_user}",
        "gists_url": "https://api.github.com/users/mdtanker/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/mdtanker",
        "id": 81199856,
        "login": "mdtanker",
        "node_id": "MDQ6VXNlcjgxMTk5ODU2",
        "organizations_url": "https://api.github.com/users/mdtanker/orgs",
        "received_events_url": "https://api.github.com/users/mdtanker/received_events",
        "repos_url": "https://api.github.com/users/mdtanker/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/mdtanker/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mdtanker/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/mdtanker"
    }
}