{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\nHi!\r\n\r\nYesterday I installed gmt6 and pygmt with conda on win10 system. It is very easy to use. I have ploted some figures with pygmt module. It is all fine until I add shading=True to pygmt.grdimage. Besides I can't pass the grid (xarray.DataArray) to call_module(\"grdgradient\") using virtual_from_grid. The error is something about \r\n\"access violation reading\",  and  I need some help to sovle this !! \r\n\r\n\r\n**code1 -> error1**\r\n![image](https://user-images.githubusercontent.com/72292548/94985041-4b79e100-0585-11eb-80ee-a0a671dd34e8.png)\r\n\r\n![image](https://user-images.githubusercontent.com/72292548/94985047-651b2880-0585-11eb-838c-eab693382e79.png)\r\n\r\n**code2->error2**\r\n![image](https://user-images.githubusercontent.com/72292548/94985114-3782af00-0586-11eb-87f7-23a1b6a98b7e.png)\r\n\r\n**System information**\r\n\r\n![image](https://user-images.githubusercontent.com/72292548/94985132-5b45f500-0586-11eb-86b5-8b8e7eed4152.png)\r\n\r\n",
    "closed_at": "2020-10-18T13:57:52Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 5,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/master/CODE_OF_CONDUCT.md).\n",
            "created_at": "2020-10-03T06:41:58Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/638#issuecomment-703056471",
            "id": 703056471,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcwMzA1NjQ3MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/703056471/reactions"
            },
            "updated_at": "2020-10-03T06:41:58Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/703056471",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I have ploted some figures with pygmt module. It is all fine until I add shading=True to pygmt.grdimage.\r\n\r\n\u4f60\u597d @liwentao-319, thanks for raising the issue and the kind words! What you are experiencing with `grdimage` shading *may* be a similar issue to #364. We tried to fix it in #581 but it appears to be an upstream issue with GMT 6.1.1, so it might take a while to fix (November 2020 probably), but it is definitely a priority for the next PyGMT v0.2.1 or v0.3.0 release.\r\n\r\nIn the meantime, if you really want `grdimage` with shading, either use pure GMT to do so, or try downgrading to GMT 6.1.0 and see if it works (though this comes with other issues).\r\n\r\n> Besides I can't pass the grid (xarray.DataArray) to call_module(\"grdgradient\") using virtual_from_grid. The error is something about \"access violation reading\", and I need some help to sovle this !!\r\n\r\nI've not seen this error before, might be a Windows thing, and I'll only have access to a Windows machine to check this. My guess is that you're on the 'E:' drive but it's trying to write to the 'C:' drive and this doesn't work. You could try without the `GMTTempFile` (just pass in a proper filepath) and see if it works, but do note that what you're using is a 'hack' and not something we support officially. If you have some time, you're welcome to submit a Pull Request to wrap `grdgradient`, I'm sure the community will greatly appreciate it :smile:\r\n\r\nAlso, in the future, please post your error messages as text instead of as a screenshot, this will help users in the future to more easily search for the same issue!",
            "created_at": "2020-10-03T21:08:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/638#issuecomment-703165006",
            "id": 703165006,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcwMzE2NTAwNg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/703165006/reactions"
            },
            "updated_at": "2020-10-07T00:46:09Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/703165006",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "OK,  I will try it and post my codes and error messages as text next time. And thanks for your reply!",
            "created_at": "2020-10-04T11:12:18Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/638#issuecomment-703239634",
            "id": 703239634,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcwMzIzOTYzNA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/703239634/reactions"
            },
            "updated_at": "2020-10-04T11:12:18Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/703239634",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/72292548?v=4",
                "events_url": "https://api.github.com/users/liwentao-319/events{/privacy}",
                "followers_url": "https://api.github.com/users/liwentao-319/followers",
                "following_url": "https://api.github.com/users/liwentao-319/following{/other_user}",
                "gists_url": "https://api.github.com/users/liwentao-319/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/liwentao-319",
                "id": 72292548,
                "login": "liwentao-319",
                "node_id": "MDQ6VXNlcjcyMjkyNTQ4",
                "organizations_url": "https://api.github.com/users/liwentao-319/orgs",
                "received_events_url": "https://api.github.com/users/liwentao-319/received_events",
                "repos_url": "https://api.github.com/users/liwentao-319/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/liwentao-319/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/liwentao-319/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/liwentao-319"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@liwentao-319 As mentioned by @weiji14, this issue may be caused by an upstream GMT bug. In PR https://github.com/GenericMappingTools/gmt/pull/4328, a related bug was fixed, and the PR may also fix the issue you're having. It would be good if you can try your scripts with the GMT development version.\r\n\r\nAs an Anaconda user, you can run `conda install -c conda-forge/label/dev gmt` to install the GMT development version. Please let us know if it solves your problems. Thanks. ",
            "created_at": "2020-10-15T07:08:39Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/638#issuecomment-708948451",
            "id": 708948451,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcwODk0ODQ1MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/708948451/reactions"
            },
            "updated_at": "2020-10-15T07:09:34Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/708948451",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "NONE",
            "body": "@seisman The command you advised works well. Thank you very much!!",
            "created_at": "2020-10-18T13:52:31Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/638#issuecomment-711171042",
            "id": 711171042,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638",
            "node_id": "MDEyOklzc3VlQ29tbWVudDcxMTE3MTA0Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/711171042/reactions"
            },
            "updated_at": "2020-10-18T13:52:31Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/711171042",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/72292548?v=4",
                "events_url": "https://api.github.com/users/liwentao-319/events{/privacy}",
                "followers_url": "https://api.github.com/users/liwentao-319/followers",
                "following_url": "https://api.github.com/users/liwentao-319/following{/other_user}",
                "gists_url": "https://api.github.com/users/liwentao-319/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/liwentao-319",
                "id": 72292548,
                "login": "liwentao-319",
                "node_id": "MDQ6VXNlcjcyMjkyNTQ4",
                "organizations_url": "https://api.github.com/users/liwentao-319/orgs",
                "received_events_url": "https://api.github.com/users/liwentao-319/received_events",
                "repos_url": "https://api.github.com/users/liwentao-319/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/liwentao-319/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/liwentao-319/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/liwentao-319"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638/comments",
    "created_at": "2020-10-03T06:41:57Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/638",
    "id": 714020589,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2020-11-14T19:32:18Z",
        "closed_issues": 58,
        "created_at": "2020-09-17T21:24:34Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/4",
        "id": 5890225,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/4/labels",
        "node_id": "MDk6TWlsZXN0b25lNTg5MDIyNQ==",
        "number": 4,
        "open_issues": 0,
        "state": "closed",
        "title": "0.2.1",
        "updated_at": "2020-12-14T00:38:58Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/4"
    },
    "node_id": "MDU6SXNzdWU3MTQwMjA1ODk=",
    "number": 638,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638/timeline",
    "title": "OSError when using pygmt.grdimage with shading=True param",
    "updated_at": "2020-10-18T13:57:52Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/638",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/72292548?v=4",
        "events_url": "https://api.github.com/users/liwentao-319/events{/privacy}",
        "followers_url": "https://api.github.com/users/liwentao-319/followers",
        "following_url": "https://api.github.com/users/liwentao-319/following{/other_user}",
        "gists_url": "https://api.github.com/users/liwentao-319/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/liwentao-319",
        "id": 72292548,
        "login": "liwentao-319",
        "node_id": "MDQ6VXNlcjcyMjkyNTQ4",
        "organizations_url": "https://api.github.com/users/liwentao-319/orgs",
        "received_events_url": "https://api.github.com/users/liwentao-319/received_events",
        "repos_url": "https://api.github.com/users/liwentao-319/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/liwentao-319/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/liwentao-319/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/liwentao-319"
    }
}