{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\nI ran into a segmentation fault when running `make test` locally after doing a `gmt clear all`. The problem is with the new test_plot_shapefile test added in #1695. The crash was also mentioned at https://github.com/GenericMappingTools/pygmt/pull/1695#issuecomment-1054361205.\r\n\r\nhttps://github.com/GenericMappingTools/pygmt/blob/14a494756904660663b5cde759a72d7b93709a3b/pygmt/tests/test_plot.py#L552-L554\r\n\r\nShould we add an extra line of code like `pygmt.which(\"@RidgeTest.shp @RidgeTest.shx @RidgeTest.dbf @RidgeTest.prj\")` before `fig.plot(data=\"@RidgeTest.shp\", ...)`? It seems redundant, but the alternative would be to have people go through the extra step of downloading the cache before running the tests. I'm thinking about potential new contributors who are just used to run `pytest` or `make test`, and a segfault doesn't look very good.\r\n\r\nAnother point is - Will users encounter a segfault if they try to plot a shapefile without all of the other files (shx, dbf)? Again, not a very good look.\r\n\r\n**Full code that generated the error**\r\n\r\n```bash\r\ngmt clear all\r\npytest --mpl --verbose -k 'shapefile' pygmt/tests/test_plot.py\r\n```\r\n\r\n**Full error message**\r\n\r\n```python-traceback\r\n===================================== test session starts =====================================\r\nplatform linux -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0 -- /home/username/mambaforge/envs/pygmt/bin/python\r\ncachedir: .pytest_cache\r\nMatplotlib: 3.5.1\r\nFreetype: 2.10.4\r\nrootdir: /home/username/Documents/github/pygmt, configfile: pyproject.toml\r\nplugins: mpl-0.14.0, cov-3.0.0\r\ncollected 26 items / 25 deselected / 1 selected                                               \r\n\r\npygmt/tests/test_plot.py::test_plot_shapefile Fatal Python error: Segmentation fault\r\n\r\nCurrent thread 0x00007f9f5b963740 (most recent call first):\r\n  File \"/home/username/Documents/github/pygmt/pygmt/clib/session.py\", line 498 in call_module\r\n  File \"/home/username/Documents/github/pygmt/pygmt/src/plot.py\", line 273 in plot\r\n  File \"/home/username/Documents/github/pygmt/pygmt/helpers/decorators.py\", line 725 in new_module\r\n  File \"/home/username/Documents/github/pygmt/pygmt/helpers/decorators.py\", line 585 in new_module\r\n  File \"/home/username/Documents/github/pygmt/pygmt/helpers/decorators.py\", line 872 in new_module\r\n  File \"/home/username/Documents/github/pygmt/pygmt/helpers/decorators.py\", line 804 in new_module\r\n  File \"/home/username/Documents/github/pygmt/pygmt/helpers/decorators.py\", line 804 in new_module\r\n  File \"/home/username/Documents/github/pygmt/pygmt/tests/test_plot.py\", line 553 in test_plot_shapefile\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pytest_mpl/plugin.py\", line 594 in item_function_wrapper\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/python.py\", line 192 in pytest_pyfunc_call\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_callers.py\", line 39 in _multicall\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_manager.py\", line 80 in _hookexec\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_hooks.py\", line 265 in __call__\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/python.py\", line 1718 in runtest\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 168 in pytest_runtest_call\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_callers.py\", line 39 in _multicall\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_manager.py\", line 80 in _hookexec\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_hooks.py\", line 265 in __call__\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 261 in <lambda>\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 340 in from_call\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 260 in call_runtest_hook\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 221 in call_and_report\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 132 in runtestprotocol\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/runner.py\", line 113 in pytest_runtest_protocol\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_callers.py\", line 39 in _multicall\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_manager.py\", line 80 in _hookexec\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_hooks.py\", line 265 in __call__\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/main.py\", line 347 in pytest_runtestloop\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_callers.py\", line 39 in _multicall\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_manager.py\", line 80 in _hookexec\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_hooks.py\", line 265 in __call__\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/main.py\", line 322 in _main\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/main.py\", line 268 in wrap_session\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/main.py\", line 315 in pytest_cmdline_main\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_callers.py\", line 39 in _multicall\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_manager.py\", line 80 in _hookexec\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/pluggy/_hooks.py\", line 265 in __call__\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 165 in main\r\n  File \"/home/username/mambaforge/envs/pygmt/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 188 in console_main\r\n  File \"/home/username/mambaforge/envs/pygmt/bin/pytest\", line 11 in <module>\r\n\r\nExtension modules: markupsafe._speedups, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.strptime, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, cftime._cftime, netCDF4._netCDF4, scipy._lib._ccallback_c, scipy.sparse._sparsetools, scipy.sparse._csparsetools, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.io.matlab._mio_utils, scipy.io.matlab._streams, scipy.io.matlab._mio5_utils, matplotlib._image, sip, PyQt5.sip, PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets (total: 80)\r\nSegmentation fault (core dumped)\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.5.1.dev144+gb58af8bf5.d20220306\r\nSystem information:\r\n  python: 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:28:35) [GCC 9.4.0]\r\n  executable: /home/username/mambaforge/envs/pygmt/bin/python\r\n  machine: Linux-5.15.0-18-generic-x86_64-with-glibc2.35\r\nDependency information:\r\n  numpy: 1.22.2\r\n  pandas: 1.4.1\r\n  xarray: 2022.3.0\r\n  netCDF4: 1.5.8\r\n  packaging: 21.3\r\n  ghostscript: 9.54.0\r\n  gmt: 6.3.0\r\nGMT library information:\r\n  binary dir: /home/username/mambaforge/envs/pygmt/bin\r\n  cores: 12\r\n  grid layout: rows\r\n  library path: /home/username/mambaforge/envs/pygmt/lib/libgmt.so\r\n  padding: 2\r\n  plugin dir: /home/username/mambaforge/envs/pygmt/lib/gmt/plugins\r\n  share dir: /home/username/mambaforge/envs/pygmt/share/gmt\r\n  version: 6.3.0\r\n```\r\n",
    "closed_at": "2022-03-07T02:47:53Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 1,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "> hould we add an extra line of code like `pygmt.which(\"@RidgeTest.shp @RidgeTest.shx @RidgeTest.dbf @RidgeTest.prj\")` before `fig.plot(data=\"@RidgeTest.shp\", ...)`? It seems redundant, but the alternative would be to have people go through the extra step of downloading the cache before running the tests.\r\n\r\nSounds good.\r\n\r\n> Will users encounter a segfault if they try to plot a shapefile without all of the other files (shx, dbf)?\r\n\r\nYes, and was reported in https://github.com/GenericMappingTools/gmt/issues/6400.",
            "created_at": "2022-03-06T16:56:17Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1788#issuecomment-1059998262",
            "id": 1059998262,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788",
            "node_id": "IC_kwDOBRZfO84_Lko2",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1059998262/reactions"
            },
            "updated_at": "2022-03-06T16:56:17Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1059998262",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788/comments",
    "created_at": "2022-03-06T16:31:51Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1788",
    "id": 1160654677,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2022-03-15T23:17:52Z",
        "closed_issues": 174,
        "created_at": "2021-06-23T03:22:20Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/9",
        "id": 6880166,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/9/labels",
        "node_id": "MDk6TWlsZXN0b25lNjg4MDE2Ng==",
        "number": 9,
        "open_issues": 0,
        "state": "closed",
        "title": "0.6.0",
        "updated_at": "2022-03-15T23:17:52Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/9"
    },
    "node_id": "I_kwDOBRZfO85FLi9V",
    "number": 1788,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788/timeline",
    "title": "Segfault when running test_plot_shapefile without the dbf and shx files",
    "updated_at": "2022-03-07T02:47:53Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1788",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    }
}