{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\nAfter the following code runs, the figure cannot be displayed automatically.\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\n\r\npygmt.show_versions()\r\nfig = pygmt.Figure()\r\nfig.basemap(region=[-90, -70, 0, 20], projection=\"M15c\", frame=True)\r\nfig.coast(shorelines=True)\r\nfig.show()\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\nPASTE ERROR MESSAGE HERE\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.3.1\r\nSystem information:\r\n  python: 3.9.1 (default, Dec 11 2020, 06:28:49)  [Clang 10.0.0 ]\r\n  executable: /Users/zengxianghang/opt/miniconda3/bin/python\r\n  machine: macOS-10.16-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.20.2\r\n  pandas: 1.2.3\r\n  xarray: 0.17.0\r\n  netCDF4: 1.5.6\r\n  packaging: 20.9\r\n  ghostscript: 9.53.3\r\n  gmt: 6.1.1\r\nGMT library information:\r\n  binary dir: /Users/zengxianghang/opt/miniconda3/bin\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: /Users/zengxianghang/opt/miniconda3/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /Users/zengxianghang/opt/miniconda3/lib/gmt/plugins\r\n  share dir: /Users/zengxianghang/opt/miniconda3/share/gmt\r\n  version: 6.1.1```\r\n",
    "closed_at": "2021-04-02T01:33:16Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/62739219?v=4",
        "events_url": "https://api.github.com/users/zengxianghang/events{/privacy}",
        "followers_url": "https://api.github.com/users/zengxianghang/followers",
        "following_url": "https://api.github.com/users/zengxianghang/following{/other_user}",
        "gists_url": "https://api.github.com/users/zengxianghang/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/zengxianghang",
        "id": 62739219,
        "login": "zengxianghang",
        "node_id": "MDQ6VXNlcjYyNzM5MjE5",
        "organizations_url": "https://api.github.com/users/zengxianghang/orgs",
        "received_events_url": "https://api.github.com/users/zengxianghang/received_events",
        "repos_url": "https://api.github.com/users/zengxianghang/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/zengxianghang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zengxianghang/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/zengxianghang"
    },
    "comments": 3,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "If you're running a python script or running the codes in a Python interpreter, you need to use `fig.show(method=\"external\")`.\r\n\r\nDuplicate of #366, and should be fixed in #529.\r\n",
            "created_at": "2021-04-02T01:11:40Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1159#issuecomment-812262860",
            "id": 812262860,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxMjI2Mjg2MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/812262860/reactions"
            },
            "updated_at": "2021-04-02T01:13:47Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/812262860",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "NONE",
            "body": "I still get  an error!\r\n\r\n```\r\nimport pygmt\r\n\r\nfig = pygmt.Figure()\r\n\r\nfig.basemap(region=[-90,-70,0,20], projection=\"M8i\", frame=True)\r\nfig.coast(shorelines=True)\r\n\r\nfig.show(method=\"external\")\r\n```\r\n\r\n![image](https://user-images.githubusercontent.com/22060413/163666833-2cd19fb5-fa64-490c-90dc-9dea482fe4d4.png)\r\n",
            "created_at": "2022-04-16T07:49:48Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1159#issuecomment-1100598310",
            "id": 1100598310,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159",
            "node_id": "IC_kwDOBRZfO85Bmcwm",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1100598310/reactions"
            },
            "updated_at": "2022-04-16T07:49:48Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1100598310",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/22060413?v=4",
                "events_url": "https://api.github.com/users/Khalilsqu/events{/privacy}",
                "followers_url": "https://api.github.com/users/Khalilsqu/followers",
                "following_url": "https://api.github.com/users/Khalilsqu/following{/other_user}",
                "gists_url": "https://api.github.com/users/Khalilsqu/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Khalilsqu",
                "id": 22060413,
                "login": "Khalilsqu",
                "node_id": "MDQ6VXNlcjIyMDYwNDEz",
                "organizations_url": "https://api.github.com/users/Khalilsqu/orgs",
                "received_events_url": "https://api.github.com/users/Khalilsqu/received_events",
                "repos_url": "https://api.github.com/users/Khalilsqu/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Khalilsqu/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Khalilsqu/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Khalilsqu"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I still get an error!\r\n> \r\n> ```\r\n> import pygmt\r\n> \r\n> fig = pygmt.Figure()\r\n> \r\n> fig.basemap(region=[-90,-70,0,20], projection=\"M8i\", frame=True)\r\n> fig.coast(shorelines=True)\r\n> \r\n> fig.show(method=\"external\")\r\n> ```\r\n> \r\n> ![image](https://user-images.githubusercontent.com/22060413/163666833-2cd19fb5-fa64-490c-90dc-9dea482fe4d4.png)\r\n\r\nMaybe `fig.show(method=\"external\", waiting=1.0)` works for you. See https://www.pygmt.org/dev/api/generated/pygmt.Figure.show.html for detailed explanations.",
            "created_at": "2022-04-16T11:50:30Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1159#issuecomment-1100647317",
            "id": 1100647317,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159",
            "node_id": "IC_kwDOBRZfO85BmouV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1100647317/reactions"
            },
            "updated_at": "2022-04-16T11:50:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1100647317",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159/comments",
    "created_at": "2021-04-02T00:57:02Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1159",
    "id": 848883657,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "cccccc",
            "default": true,
            "description": "This issue or pull request already exists",
            "id": 563309828,
            "name": "duplicate",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjg=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/duplicate"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU4NDg4ODM2NTc=",
    "number": 1159,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159/timeline",
    "title": "fig.show() not work",
    "updated_at": "2022-04-16T11:50:30Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1159",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/62739219?v=4",
        "events_url": "https://api.github.com/users/zengxianghang/events{/privacy}",
        "followers_url": "https://api.github.com/users/zengxianghang/followers",
        "following_url": "https://api.github.com/users/zengxianghang/following{/other_user}",
        "gists_url": "https://api.github.com/users/zengxianghang/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/zengxianghang",
        "id": 62739219,
        "login": "zengxianghang",
        "node_id": "MDQ6VXNlcjYyNzM5MjE5",
        "organizations_url": "https://api.github.com/users/zengxianghang/orgs",
        "received_events_url": "https://api.github.com/users/zengxianghang/received_events",
        "repos_url": "https://api.github.com/users/zengxianghang/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/zengxianghang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zengxianghang/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/zengxianghang"
    }
}