{
    "active_lock_reason": null,
    "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "assignees": [
        {
            "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
            "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
            "followers_url": "https://api.github.com/users/weiji14/followers",
            "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
            "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/weiji14",
            "id": 23487320,
            "login": "weiji14",
            "node_id": "MDQ6VXNlcjIzNDg3MzIw",
            "organizations_url": "https://api.github.com/users/weiji14/orgs",
            "received_events_url": "https://api.github.com/users/weiji14/received_events",
            "repos_url": "https://api.github.com/users/weiji14/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/weiji14"
        }
    ],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\nWhen I using the x2sys_cross function, passing a pandas.DataFrame I got no result return. However, passing an ASCII file the the program works fine. I don't know what went wrong, and I  tested the code of pull request#591 it worked.\r\nI upload the **ssh.txt** for running the above code. See my **testdata repertory**. https://github.com/isLiYang/testdata\r\n\r\nI hope someone can solve my question.\r\n\r\nThank You.\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport numpy as np\r\nimport pandas as pd\r\nimport pygmt\r\nimport os\r\nfrom tempfile import TemporaryDirectory\r\n\r\n# load my data.\r\ndata = np.loadtxt('ssh.txt')\r\ndf = pd.DataFrame({\r\n    'lon': data[:, 0],\r\n    'lat': data[:, 1],\r\n    'ssh': data[:, 2]\r\n})\r\ndf.columns = ['lon', 'lat', 'z']\r\n\r\n\r\n# load test data from: Pull request #591.\r\n# https://github.com/GenericMappingTools/pygmt/pull/591\r\ndataframe: pd.DataFrame = pygmt.datasets.load_sample_bathymetry()\r\ndataframe.columns = [\"x\", \"y\", \"z\"]  # longitude, latitude, bathymetry\r\n\r\n\r\n# Test plll resuest #591, it works fine.\r\nos.environ[\"X2SYS_HOME\"] = os.getcwd()\r\n\r\nwith TemporaryDirectory(prefix=\"X2SYS\", dir=os.environ[\"X2SYS_HOME\"]) as tmpdir:\r\n    tag = os.path.basename(tmpdir)\r\n    pygmt.x2sys_init(tag=tag, fmtfile=\"xyz\", suffix=\"xyz\", force=True)\r\n    output: pd.DataFrame = pygmt.x2sys_cross(tracks=[dataframe], tag=tag, coe=\"i\", verbose=\"i\")\r\n\r\n\r\n# test my data.\r\n# 1.When passing a ascii file, the calculation is fine and the ascii file and the dataframe object can be output.\r\nos.environ[\"X2SYS_HOME\"] = os.getcwd()\r\nwith TemporaryDirectory(prefix=\"X2SYS\", dir=os.environ[\"X2SYS_HOME\"]) as tmpdir:\r\n    tag = os.path.basename(tmpdir)\r\n    # passing file.\r\n    pygmt.x2sys_init(tag=tag, fmtfile='geoz', suffix='txt', force=True, discontinuity='g', gap=['d100'], verbose='i')\r\n    pygmt.x2sys_cross(tracks=['ssh.txt'], outfile='pyxovers1.dat', tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n    xovers1 = pygmt.x2sys_cross(tracks=['ssh.txt'], tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n\r\n\r\n# 2.When passing a dataframe, it will not output the result of the calculation or report an error.\r\nos.environ[\"X2SYS_HOME\"] = os.getcwd()\r\nwith TemporaryDirectory(prefix=\"X2SYS\", dir=os.environ[\"X2SYS_HOME\"]) as tmpdir:\r\n    tag = os.path.basename(tmpdir)\r\n    # passing file.\r\n    pygmt.x2sys_init(tag=tag, fmtfile='geoz', force=True, discontinuity='g', gap=['d100'], verbose='i')\r\n    pygmt.x2sys_cross(tracks=[df], outfile='pyxovers2.dat', tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n    xovers2 = pygmt.x2sys_cross(tracks=[df], tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n\r\nprint('finished...')\r\n\r\n\r\n```\r\n\r\n**Full error message**\r\n**pyxovers2.dat** will be created, but no data in there. \r\nbelow are message of \r\n```python\r\npygmt.x2sys_cross(tracks=[df], outfile='pyxovers2.dat', tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n```\r\nand\r\n```python\r\n    xovers2 = pygmt.x2sys_cross(tracks=[df], tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n```\r\n```\r\nx2sys_cross [INFORMATION]: Files found: 1\r\nx2sys_cross [INFORMATION]: Checking for duplicates :\r\nx2sys_cross [INFORMATION]: 0 found\r\nx2sys_cross [WARNING]: No time column, use dummy times\r\nx2sys_cross [INFORMATION]: Writing Data Table to file pyxovers2.dat\r\nx2sys_cross [INFORMATION]: Files found: 1\r\nx2sys_cross [INFORMATION]: Checking for duplicates :\r\nx2sys_cross [INFORMATION]: 0 found\r\nx2sys_cross [WARNING]: No time column, use dummy times\r\nx2sys_cross [INFORMATION]: Writing Data Table to file /tmp/pygmt-4qfsz7oy.txt\r\nTraceback (most recent call last):\r\n  File \"/mnt/e/HY2A/tmp.py\", line 50, in <module>\r\n    xovers2 = pygmt.x2sys_cross(tracks=[df], tag=tag, interpolation='a', verbose='i', region='g', trackvalues=True)\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pygmt/helpers/decorators.py\", line 414, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pygmt/helpers/decorators.py\", line 557, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pygmt/src/x2sys_cross.py\", line 228, in x2sys_cross\r\n    table = pd.read_csv(\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pandas/io/parsers.py\", line 610, in read_csv\r\n    return _read(filepath_or_buffer, kwds)\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pandas/io/parsers.py\", line 462, in _read\r\n    parser = TextFileReader(filepath_or_buffer, **kwds)\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pandas/io/parsers.py\", line 819, in __init__\r\n    self._engine = self._make_engine(self.engine)\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pandas/io/parsers.py\", line 1050, in _make_engine\r\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\r\n  File \"/home/liyang/anaconda3/envs/pygmt/lib/python3.9/site-packages/pandas/io/parsers.py\", line 1873, in __init__\r\n    self._reader = parsers.TextReader(self.handles.handle, **kwds)\r\n  File \"pandas/_libs/parsers.pyx\", line 521, in pandas._libs.parsers.TextReader.__cinit__\r\npandas.errors.EmptyDataError: No columns to parse from file\r\n\r\nProcess finished with exit code 1\r\n\r\n```\r\n\r\n**System information**\r\n```\r\nPyGMT information:\r\n  version: v0.4.0\r\nSystem information:\r\n  python: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0]\r\n  executable: /home/liyang/anaconda3/envs/pygmt/bin/python\r\n  machine: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31\r\nDependency information:\r\n  numpy: 1.20.2\r\n  pandas: 1.2.5\r\n  xarray: 0.18.2\r\n  netCDF4: 1.5.7\r\n  packaging: 20.9\r\n  ghostscript: 9.54.0\r\n  gmt: 6.2.0\r\nGMT library information:\r\n  binary dir: /home/liyang/anaconda3/envs/pygmt/bin\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: /home/liyang/anaconda3/envs/pygmt/lib/libgmt.so\r\n  padding: 2\r\n  plugin dir: /home/liyang/anaconda3/envs/pygmt/lib/gmt/plugins\r\n  share dir: /home/liyang/anaconda3/envs/pygmt/share/gmt\r\n  version: 6.2.0\r\n```\r\n\r\n",
    "closed_at": "2021-07-09T21:32:59Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "comments": 5,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/master/CODE_OF_CONDUCT.md).\n",
            "created_at": "2021-07-04T03:28:55Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1368#issuecomment-873508290",
            "id": 873508290,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg3MzUwODI5MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873508290/reactions"
            },
            "updated_at": "2021-07-04T03:28:55Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873508290",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @isLiYang, thanks for filing this bug report! I can reproduce your error, and have tracked down the problem to this section of the code:\r\n\r\nhttps://github.com/GenericMappingTools/pygmt/blob/d90b3fc889b53633deab6b4ab77612ac7a247c1b/pygmt/src/x2sys_cross.py#L46-L51\r\n\r\nThe problem is that PyGMT was not handling the NaN values in your dataframe properly. By default, `pandas.to_csv` writes out blank '' NaN values, instead of the word NaN to file, but GMT requires an explicit NaN value in the file in order to understand it. The solution is relatively simple, just add `na_rep=\"NaN\"` to the track.to_csv` call so that NaN values are printed. I will submit a fix for this bug shortly (edit: done at #1369).\r\n\r\nIn the meantime, I would suggest using `ssh.txt` as input to x2sys_cross for PyGMT v0.4.0. Alternatively, you may also consider doing `df = df.dropna()` to remove the NaN values in your lon/lat/ssh dataset, but that would not give you the crossover locations of points with missing values (which may be ok or not ok, depending on what you want to do with your dataset).\r\n",
            "created_at": "2021-07-04T23:44:27Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1368#issuecomment-873687026",
            "id": 873687026,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg3MzY4NzAyNg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873687026/reactions"
            },
            "updated_at": "2021-07-05T01:01:46Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873687026",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "Thank you for your reply.\r\nI will try to remove NaN values in pandas.Dataframe When using x2sys module, deleting NaN values doesn't affect my calculations.\r\nThank you for your contributions to open source software.\r\n@weiji14 ",
            "created_at": "2021-07-05T01:22:56Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1368#issuecomment-873715567",
            "id": 873715567,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg3MzcxNTU2Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873715567/reactions"
            },
            "updated_at": "2021-07-05T01:22:56Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873715567",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/69391863?v=4",
                "events_url": "https://api.github.com/users/isLiYang/events{/privacy}",
                "followers_url": "https://api.github.com/users/isLiYang/followers",
                "following_url": "https://api.github.com/users/isLiYang/following{/other_user}",
                "gists_url": "https://api.github.com/users/isLiYang/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/isLiYang",
                "id": 69391863,
                "login": "isLiYang",
                "node_id": "MDQ6VXNlcjY5MzkxODYz",
                "organizations_url": "https://api.github.com/users/isLiYang/orgs",
                "received_events_url": "https://api.github.com/users/isLiYang/received_events",
                "repos_url": "https://api.github.com/users/isLiYang/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/isLiYang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/isLiYang/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/isLiYang"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Cool, and let us know if you need any other help, or if there's another `x2sys` module at https://docs.generic-mapping-tools.org/6.2/modules.html#x2sys you need and we'll put in a feature request :smile:\r\n\r\nP.S. I'll reopen this issue until the bugfix at #1369 is incorporated to PyGMT's main branch.",
            "created_at": "2021-07-05T01:32:47Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1368#issuecomment-873718839",
            "id": 873718839,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg3MzcxODgzOQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873718839/reactions"
            },
            "updated_at": "2021-07-05T01:32:47Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/873718839",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "@weiji14 \r\n\ud83d\ude01 Haha. That sounds great, but I don't need any of the other functions of x2sys module right now. It is better to develop some commonly used functions first. ",
            "created_at": "2021-07-05T12:04:36Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1368#issuecomment-874059487",
            "id": 874059487,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg3NDA1OTQ4Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/874059487/reactions"
            },
            "updated_at": "2021-07-05T12:04:36Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/874059487",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/69391863?v=4",
                "events_url": "https://api.github.com/users/isLiYang/events{/privacy}",
                "followers_url": "https://api.github.com/users/isLiYang/followers",
                "following_url": "https://api.github.com/users/isLiYang/following{/other_user}",
                "gists_url": "https://api.github.com/users/isLiYang/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/isLiYang",
                "id": 69391863,
                "login": "isLiYang",
                "node_id": "MDQ6VXNlcjY5MzkxODYz",
                "organizations_url": "https://api.github.com/users/isLiYang/orgs",
                "received_events_url": "https://api.github.com/users/isLiYang/received_events",
                "repos_url": "https://api.github.com/users/isLiYang/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/isLiYang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/isLiYang/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/isLiYang"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368/comments",
    "created_at": "2021-07-04T03:28:54Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1368",
    "id": 936368101,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2021-08-10T13:53:39Z",
        "closed_issues": 37,
        "created_at": "2021-07-24T06:36:35Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/29518865?v=4",
            "events_url": "https://api.github.com/users/willschlitzer/events{/privacy}",
            "followers_url": "https://api.github.com/users/willschlitzer/followers",
            "following_url": "https://api.github.com/users/willschlitzer/following{/other_user}",
            "gists_url": "https://api.github.com/users/willschlitzer/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/willschlitzer",
            "id": 29518865,
            "login": "willschlitzer",
            "node_id": "MDQ6VXNlcjI5NTE4ODY1",
            "organizations_url": "https://api.github.com/users/willschlitzer/orgs",
            "received_events_url": "https://api.github.com/users/willschlitzer/received_events",
            "repos_url": "https://api.github.com/users/willschlitzer/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/willschlitzer/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/willschlitzer/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/willschlitzer"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/10",
        "id": 7000367,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/10/labels",
        "node_id": "MI_kwDOBRZfO84AatEv",
        "number": 10,
        "open_issues": 0,
        "state": "closed",
        "title": "0.4.1",
        "updated_at": "2021-10-03T10:47:38Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/10"
    },
    "node_id": "MDU6SXNzdWU5MzYzNjgxMDE=",
    "number": 1368,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368/timeline",
    "title": "Bug with x2sys_cross module not handling NaN values properly",
    "updated_at": "2021-07-25T20:17:52Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1368",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/69391863?v=4",
        "events_url": "https://api.github.com/users/isLiYang/events{/privacy}",
        "followers_url": "https://api.github.com/users/isLiYang/followers",
        "following_url": "https://api.github.com/users/isLiYang/following{/other_user}",
        "gists_url": "https://api.github.com/users/isLiYang/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/isLiYang",
        "id": 69391863,
        "login": "isLiYang",
        "node_id": "MDQ6VXNlcjY5MzkxODYz",
        "organizations_url": "https://api.github.com/users/isLiYang/orgs",
        "received_events_url": "https://api.github.com/users/isLiYang/received_events",
        "repos_url": "https://api.github.com/users/isLiYang/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/isLiYang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/isLiYang/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/isLiYang"
    }
}