{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of proposed changes**\r\n\r\nAll PyGMT tests, excluding a few marked as `xfail` or `xskip`, should pass on all platforms (Linux/macOS/Windows).\r\n\r\nHowever, the tests sometimes fail on Windows. Generally, there are two different types of failures:\r\n\r\n1. as reported in https://github.com/GenericMappingTools/pygmt/issues/717, calling the GMT library sometimes raises the error\r\n   `OSError: exception: access violation reading 0x000001E880146FBC`. \r\n   It's difficult to debug, as none of us are developing PyGMT on Windows.\r\n2. Tests that calling `grdcut` and/or `grdfilter` sometimes fail, with the error messages shown below. It turns out that the file exists but has a zero size, so it's an invalid netCDF file. However, it's still puzzling why the file size is zero.\r\n\r\n```\r\nWARNING: D:\\a\\pygmt\\pygmt\\examples\\tutorials\\3d-perspective-image.py failed to execute correctly: Traceback (most recent call last):\r\n  File \"D:\\a\\pygmt\\pygmt\\examples\\tutorials\\3d-perspective-image.py\", line 12, in <module>\r\n    grid = pygmt.datasets.load_earth_relief(resolution=\"05m\", region=[-108, -103, 35, 40])\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\pygmt\\helpers\\decorators.py\", line 411, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\pygmt\\datasets\\earth_relief.py\", line 103, in load_earth_relief\r\n    grid = grdcut(f\"@earth_relief_{resolution}{reg}\", region=region)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\pygmt\\helpers\\decorators.py\", line 270, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\pygmt\\helpers\\decorators.py\", line 411, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\pygmt\\gridops.py\", line 112, in grdcut\r\n    with xr.open_dataarray(outgrid) as dataarray:\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\api.py\", line 701, in open_dataarray\r\n    dataset = open_dataset(\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\api.py\", line 572, in open_dataset\r\n    store = opener(filename_or_obj, **extra_kwargs, **backend_kwargs)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\netCDF4_.py\", line 364, in open\r\n    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\netCDF4_.py\", line 314, in __init__\r\n    self.format = self.ds.data_model\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\netCDF4_.py\", line 373, in ds\r\n    return self._acquire()\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\netCDF4_.py\", line 367, in _acquire\r\n    with self._manager.acquire_context(needs_lock) as root:\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\contextlib.py\", line 113, in __enter__\r\n    return next(self.gen)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\file_manager.py\", line 187, in acquire_context\r\n    file, cached = self._acquire_with_cache_info(needs_lock)\r\n  File \"C:\\Miniconda3\\envs\\test\\lib\\site-packages\\xarray\\backends\\file_manager.py\", line 205, in _acquire_with_cache_info\r\n    file = self._opener(*self._args, **kwargs)\r\n  File \"netCDF4\\_netCDF4.pyx\", line 2357, in netCDF4._netCDF4.Dataset.__init__\r\n  File \"netCDF4\\_netCDF4.pyx\", line 1925, in netCDF4._netCDF4._ensure_nc_success\r\nOSError: [Errno -51] NetCDF: Unknown file format: b'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\pygmt-ix6yj56l.nc'\r\n```\r\n\r\n**Reminders**\r\n\r\n- [ ] Run `make format` and `make check` to make sure the code follows the style guide.\r\n- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.\r\n- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.\r\n- [ ] Write detailed docstrings for all functions/methods.\r\n- [ ] If adding new functionality, add an example to docstrings or tutorials.\r\n\r\n**Notes**\r\n\r\n- You can write `/format` in the first line of a comment to lint the code automatically\r\n",
    "closed_at": "2021-02-28T21:59:21Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 21,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "It's really weird. I just added some print statements to the `grdcut` function (please check the changed files), and now more tests fail (some are expected, while others are not).\r\n\r\nOne of the print statement is:\r\n```\r\n                print(arg_str, tmpfile.name)\r\n```\r\n`arg_str` is the argument string passed to `grdcut`, and `tmpfile.name` is the filename used in building the `-G` argument. So we should expect to see that `arg_str` contains `tmpfile.name`.\r\n\r\nTest output: https://github.com/GenericMappingTools/pygmt/actions/runs/436592267\r\n\r\nFor some tests, the output looks correct:\r\n```\r\n______________________ test_earth_relief_05m_with_region _______________________\r\n----------------------------- Captured stdout call -----------------------------\r\n@earth_relief_05m_g -G/tmp/pygmt-4_6b511z.nc -R120/160/30/60 /tmp/pygmt-4_6b511z.nc\r\nTrue\r\n303069\r\n/tmp/pygmt-4_6b511z.nc: Title: Produced by grdcut\r\n/tmp/pygmt-4_6b511z.nc: Command: grdcut @earth_relief_05m_g/ -G/tmp/pygmt-4_6b511z.nc -R120/160/30/60\r\n/tmp/pygmt-4_6b511z.nc: Remark: \r\n/tmp/pygmt-4_6b511z.nc: Gridline node registration used [Geographic grid]\r\n/tmp/pygmt-4_6b511z.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7\r\n/tmp/pygmt-4_6b511z.nc: x_min: 120 x_max: 160 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 481\r\n/tmp/pygmt-4_6b511z.nc: y_min: 30 y_max: 60 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 361\r\n/tmp/pygmt-4_6b511z.nc: z_min: -9633 z_max: 2532 name: z\r\n/tmp/pygmt-4_6b511z.nc: scale_factor: 1 add_offset: 0\r\n/tmp/pygmt-4_6b511z.nc: format: netCDF-4 chunk_size: 161,181 shuffle: on deflation_level: 3\r\n```\r\n\r\nHowever, for some tests, it seems `tmpfile.name` contains random values.\r\n\r\nFor example, in the test below, the expected `tmpfile.name` is `/tmp/pygmt-lgnw8qf8.nc`, but the actual value is ` /tmp/pygmt-225d90oz.nc`.\r\n\r\n```\r\n_________________________ test_grdcut_file_in_file_out _________________________\r\n----------------------------- Captured stdout call -----------------------------\r\n@earth_relief_01d -G/tmp/pygmt-lgnw8qf8.nc -R0/180/0/90 /tmp/pygmt-225d90oz.nc\r\nTrue\r\n0\r\n----------------------------- Captured stderr call -----------------------------\r\nERROR 4: `/tmp/pygmt-225d90oz.nc' not recognized as a supported file format.\r\ngrdinfo (gmtapi_import_grid): Not a supported grid format [/tmp/pygmt-225d90oz.nc]\r\n[Session pygmt-session (657)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)\r\n[Session pygmt-session (657)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)\r\n```\r\n\r\n**EDIT:** The `-G/tmp/pygmt-lgnw8qf8.nc` and `/tmp/pygmt-225d90oz.nc` are different, because `/tmp/pygmt-lgnw8qf8.nc` was passed from the calling function.",
            "created_at": "2020-12-21T20:42:04Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-749186664",
            "id": 749186664,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc0OTE4NjY2NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/749186664/reactions"
            },
            "updated_at": "2020-12-22T15:47:04Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/749186664",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Sad. I can't reproduce the random Windows failures in this branch.",
            "created_at": "2020-12-21T22:48:22Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-749240041",
            "id": 749240041,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc0OTI0MDA0MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/749240041/reactions"
            },
            "updated_at": "2020-12-22T15:47:15Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/749240041",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "/test-gmt-dev",
            "created_at": "2021-02-02T08:19:28Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-771455791",
            "id": 771455791,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MTQ1NTc5MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 1,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/771455791/reactions"
            },
            "updated_at": "2021-02-02T09:10:23Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/771455791",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "/test-gmt-dev try 2",
            "created_at": "2021-02-02T08:38:48Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-771466722",
            "id": 771466722,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MTQ2NjcyMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 1,
                "total_count": 3,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/771466722/reactions"
            },
            "updated_at": "2021-02-02T09:10:31Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/771466722",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "/test-gmt-dev try 3",
            "created_at": "2021-02-02T09:10:05Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-771485549",
            "id": 771485549,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MTQ4NTU0OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 1,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/771485549/reactions"
            },
            "updated_at": "2021-02-03T08:57:07Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/771485549",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "/test-gmt-dev try 4",
            "created_at": "2021-02-03T08:57:14Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-772345559",
            "id": 772345559,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MjM0NTU1OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 1,
                "total_count": 3,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772345559/reactions"
            },
            "updated_at": "2021-02-03T09:30:49Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772345559",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "/test-gmt-dev try 5",
            "created_at": "2021-02-03T09:30:56Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-772366652",
            "id": 772366652,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MjM2NjY1Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 1,
                "total_count": 3,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772366652/reactions"
            },
            "updated_at": "2021-02-03T09:30:56Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772366652",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Windows tests still failing with `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\pygmt-9nbjsh8w.nc'` (see https://github.com/GenericMappingTools/pygmt/runs/1821361588?check_suite_focus=true#step:14:433).\r\n\r\nI've been reading up the threads at https://github.com/astropy/astropy/issues/7404 and https://github.com/joblib/joblib/issues/806 and *think* it might related to how we are reading in the grids using `xarray.open_dataarray` via a hidden `memmap` setting. It's really hard to debug because 1) Few of us are good on Windows and 2) The issue is very random/intermittent. Even if we manage to find a way to disable `memmap` reading, we need a good way to set `memmap=False` only on Windows. The `memmap` is actually a useful feature to conserve RAM so we might want to keep it enabled on Linux/macOS if possible.",
            "created_at": "2021-02-03T21:38:54Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-772841966",
            "id": 772841966,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3Mjg0MTk2Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772841966/reactions"
            },
            "updated_at": "2021-02-03T21:38:54Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772841966",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> The issue is very random/intermittent\r\n\r\nI think the tests fail randomly with GMT 6.1.1, but **always** fail with GMT dev, and the error messages are also different.",
            "created_at": "2021-02-03T22:03:08Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-772855781",
            "id": 772855781,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3Mjg1NTc4MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772855781/reactions"
            },
            "updated_at": "2021-02-03T22:03:08Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772855781",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> > The issue is very random/intermittent\r\n> \r\n> I think the tests fail randomly with GMT 6.1.1, but **always** fail with GMT dev, and the error messages are also different.\r\n\r\nOk, then best to test on GMT dev (6.2.0) which consistently fails (rather than waiting for random failures), the PermissionError I got above is from the GMT Latest/Dev tests actually. I'll need try to resolve #829 locally on my end to be able to debug this :disappointed:",
            "created_at": "2021-02-03T22:16:17Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-772863782",
            "id": 772863782,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3Mjg2Mzc4Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772863782/reactions"
            },
            "updated_at": "2021-02-03T22:16:17Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772863782",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Ok, so the tests on GMT Dev 6.2.0 started failing on 13 January 2021 (see https://github.com/GenericMappingTools/pygmt/runs/1691984838?check_suite_focus=true#step:12:437), the previous one on 12 January 2021 was fine (https://github.com/GenericMappingTools/pygmt/runs/1685025652?check_suite_focus=true#step:12:727):\r\n\r\n![image](https://user-images.githubusercontent.com/23487320/106845416-c4de3780-670f-11eb-9f60-daf23941cc9d.png)\r\n\r\nThe commits on GMT around that date (see https://github.com/GenericMappingTools/gmt/commits/master?after=1456fa60dd7ff0722e53b1e93e983c35b54b10a4+34&branch=master) are as follows:\r\n\r\n![image](https://user-images.githubusercontent.com/23487320/106845578-15ee2b80-6710-11eb-8c69-f12669c663b7.png)\r\n\r\nThe Python dependencies (e.g. `xarray`) doesn't appeared to have changed, and there wasn't any commits to PyGMT's master branch between 8 Jan and 16 Jan 2021. So maybe https://github.com/GenericMappingTools/gmt/pull/4646 or https://github.com/GenericMappingTools/gmt/pull/4647 introduced a bug (leaning towards the latter)?",
            "created_at": "2021-02-04T04:48:28Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773025666",
            "id": 773025666,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzAyNTY2Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773025666/reactions"
            },
            "updated_at": "2021-02-04T04:50:10Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773025666",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> So maybe [GenericMappingTools/gmt#4646](https://github.com/GenericMappingTools/gmt/pull/4646) or [GenericMappingTools/gmt#4647](https://github.com/GenericMappingTools/gmt/pull/4647) introduced a bug (leaning towards the latter)?\r\n\r\nWe're using the GMT dev build from conda-forge's dev channel. It seems at that date we bumped `gmt-6.2.0.dev5+c94e83f` to `gmt-6.2.0.dev6+98bb060` (https://github.com/conda-forge/gmt-feedstock/pull/129).",
            "created_at": "2021-02-04T04:53:20Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773027256",
            "id": 773027256,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzAyNzI1Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773027256/reactions"
            },
            "updated_at": "2021-02-04T04:54:39Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773027256",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Ah ok, so from PR https://github.com/conda-forge/gmt-feedstock/pull/129 then. There's 117 commits in between 29 Nov 2020 to 12 January 2021 to check at https://github.com/GenericMappingTools/gmt/compare/c94e83f3537c3a5ddadd3641d1b9aaec003b4bef...98bb060828eeb6fe0e7f80d49223e45c567f0632 \ud83d\ude05. List of candidates:\r\n\r\n- https://github.com/GenericMappingTools/gmt/pull/4590\r\n- https://github.com/GenericMappingTools/gmt/pull/4576",
            "created_at": "2021-02-04T04:56:53Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773028340",
            "id": 773028340,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzAyODM0MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773028340/reactions"
            },
            "updated_at": "2021-02-04T05:03:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773028340",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> There's 117 commits in between 29 Nov 2020 to 12 January 2021\r\n\r\nPerhaps it's easier to test on the GMT side. The GMT CI is building the GMT codes on Windows, so what we need to do is:\r\n\r\n- Install anaconda and pygmt dependencies (except gmt)\r\n- Install PyGMT\r\n- Let PyGMT use the GMT built from source codes\r\n- Run PyGMT tests\r\n\r\nEdit: Trying in https://github.com/GenericMappingTools/gmt/pull/4745\r\n",
            "created_at": "2021-02-04T05:12:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773033777",
            "id": 773033777,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzAzMzc3Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773033777/reactions"
            },
            "updated_at": "2021-02-04T05:22:52Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773033777",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Perhaps it's easier to test on the GMT side. The GMT CI is building the GMT codes on Windows, so what we need to do is:\r\n> \r\n>     * Install anaconda and pygmt dependencies (except gmt)\r\n> \r\n>     * Install PyGMT\r\n> \r\n>     * Let PyGMT use the GMT built from source codes\r\n> \r\n>     * Run PyGMT tests\r\n\r\nNot quite sure I get you. Do you mean compiling each of 117 GMT dev versions and testing it with PyGMT? That seems like a lot of computing power needed...",
            "created_at": "2021-02-04T05:24:44Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773038662",
            "id": 773038662,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzAzODY2Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773038662/reactions"
            },
            "updated_at": "2021-02-04T05:24:44Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773038662",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Do you mean compiling each of 117 GMT dev versions and testing it with PyGMT? That seems like a lot of computing power needed...\r\n\r\nWe can use binary search to reduce the number of builds. Ideally, we can find the bug in less than 7 builds (2**7=128 > 117, the math may be wrong).  ",
            "created_at": "2021-02-04T05:30:25Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773041237",
            "id": 773041237,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzA0MTIzNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773041237/reactions"
            },
            "updated_at": "2021-02-04T05:30:25Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773041237",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> > Do you mean compiling each of 117 GMT dev versions and testing it with PyGMT? That seems like a lot of computing power needed...\n> \n> We can use binary search to reduce the number of builds. Ideally, we can find the bug in less than 7 builds (2**7=128 > 117, the math may be wrong).  \n\nVery smart! Let us know when you find it.",
            "created_at": "2021-02-04T11:11:06Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773228421",
            "id": 773228421,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzIyODQyMQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773228421/reactions"
            },
            "updated_at": "2021-02-04T11:11:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773228421",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Based on the tests in https://github.com/GenericMappingTools/gmt/pull/4745, https://github.com/GenericMappingTools/gmt/commit/b16cc28b4b62b22f6e6f45584d80347cec739f54 (i.e., https://github.com/GenericMappingTools/gmt/pull/4581) is the commit that introduced the bug.",
            "created_at": "2021-02-04T16:00:53Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-773416253",
            "id": 773416253,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MzQxNjI1Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773416253/reactions"
            },
            "updated_at": "2021-02-04T16:00:53Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/773416253",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Just following up, issue appears to be GMT not closing a file properly, should be fixed in https://github.com/GenericMappingTools/gmt/pull/4777.\r\n\r\nWhat we should do here in PyGMT is to remove the xfails for GMT > 6.2.0 (i.e. for the dev tests). The GMT conda-forge dev version merged at https://github.com/conda-forge/gmt-feedstock/pull/134 (and https://github.com/conda-forge/gmt-feedstock/pull/135) should include this fix so we can test it in our CI.",
            "created_at": "2021-02-28T09:38:27Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-787423965",
            "id": 787423965,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NzQyMzk2NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787423965/reactions"
            },
            "updated_at": "2021-02-28T09:41:54Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787423965",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Just following up, issue appears to be GMT not closing a file properly, should be fixed in [GenericMappingTools/gmt#4777](https://github.com/GenericMappingTools/gmt/pull/4777).\r\n> \r\n> What we should do here in PyGMT is to remove the xfails for GMT > 6.2.0 (i.e. for the dev tests). The GMT conda-forge dev version merged at [conda-forge/gmt-feedstock#134](https://github.com/conda-forge/gmt-feedstock/pull/134) (and [conda-forge/gmt-feedstock#135](https://github.com/conda-forge/gmt-feedstock/pull/135)) should include this fix so we can test it in our CI.\r\n\r\nThis PR tries to fix the **random** failures that sometimes still pass. These tests are not marked as `xfail` or `xskip`. So we can do nothing here. The good news is, I rarely see these random failures in \"GMT Dev Tests\", so it may mean that these are already fixed. ",
            "created_at": "2021-02-28T20:07:55Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-787514026",
            "id": 787514026,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NzUxNDAyNg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787514026/reactions"
            },
            "updated_at": "2021-02-28T20:07:55Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787514026",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Right, got a bit confused as we were trying so many things to see what was broken. So can we close this PR then? ",
            "created_at": "2021-02-28T21:55:18Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758#issuecomment-787530296",
            "id": 787530296,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NzUzMDI5Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787530296/reactions"
            },
            "updated_at": "2021-02-28T21:55:18Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787530296",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758/comments",
    "created_at": "2020-12-21T19:34:37Z",
    "draft": true,
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758",
    "id": 772412422,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2021-03-15T15:24:53Z",
        "closed_issues": 127,
        "created_at": "2021-02-16T07:55:18Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/29518865?v=4",
            "events_url": "https://api.github.com/users/willschlitzer/events{/privacy}",
            "followers_url": "https://api.github.com/users/willschlitzer/followers",
            "following_url": "https://api.github.com/users/willschlitzer/following{/other_user}",
            "gists_url": "https://api.github.com/users/willschlitzer/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/willschlitzer",
            "id": 29518865,
            "login": "willschlitzer",
            "node_id": "MDQ6VXNlcjI5NTE4ODY1",
            "organizations_url": "https://api.github.com/users/willschlitzer/orgs",
            "received_events_url": "https://api.github.com/users/willschlitzer/received_events",
            "repos_url": "https://api.github.com/users/willschlitzer/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/willschlitzer/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/willschlitzer/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/willschlitzer"
        },
        "description": "",
        "due_on": "2021-03-12T08:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/7",
        "id": 6437411,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/7/labels",
        "node_id": "MDk6TWlsZXN0b25lNjQzNzQxMQ==",
        "number": 7,
        "open_issues": 0,
        "state": "closed",
        "title": "0.3.1",
        "updated_at": "2021-03-15T15:24:53Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/7"
    },
    "node_id": "MDExOlB1bGxSZXF1ZXN0NTQzNjgyODkx",
    "number": 758,
    "performed_via_github_app": null,
    "pull_request": {
        "diff_url": "https://github.com/GenericMappingTools/pygmt/pull/758.diff",
        "html_url": "https://github.com/GenericMappingTools/pygmt/pull/758",
        "merged_at": null,
        "patch_url": "https://github.com/GenericMappingTools/pygmt/pull/758.patch",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/pulls/758"
    },
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758/timeline",
    "title": "WIP: Fix random failures in Windows CI ",
    "updated_at": "2021-03-01T03:16:34Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/758",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    }
}