{
    "active_lock_reason": null,
    "assignee": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "assignees": [
        {
            "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
            "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
            "followers_url": "https://api.github.com/users/weiji14/followers",
            "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
            "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/weiji14",
            "id": 23487320,
            "login": "weiji14",
            "node_id": "MDQ6VXNlcjIzNDg3MzIw",
            "organizations_url": "https://api.github.com/users/weiji14/orgs",
            "received_events_url": "https://api.github.com/users/weiji14/received_events",
            "repos_url": "https://api.github.com/users/weiji14/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/weiji14"
        }
    ],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n[xarray 0.18.0 was released on May 6, 2021](https://xarray.pydata.org/en/v0.18.0/whats-new.html), and some PyGMT tests break. I'm not sure if it's a bug or a breaking change of xarray.\r\n\r\n**Full code that generated the error**\r\n\r\nAfter upgrading to xarray 0.18.0, following codes no longer work:\r\n```python\r\nimport pygmt\r\npygmt.datasets.load_earth_relief(\"01d\")\r\n```\r\n\r\n**Full error message**\r\n\r\n```python-traceback\r\nValueError                                Traceback (most recent call last)\r\n<ipython-input-2-30e5a4024c6c> in <module>\r\n----> 1 pygmt.datasets.load_earth_relief(\"01d\")\r\n\r\npygmt/pygmt/helpers/decorators.py in new_module(*args, **kwargs)\r\n    436                         kwargs[arg] = separators[fmt].join(f\"{item}\" for item in value)\r\n    437             # Execute the original function and return its output\r\n--> 438             return module_func(*args, **kwargs)\r\n    439\r\n    440         return new_module\r\n\r\npygmt/pygmt/datasets/earth_relief.py in load_earth_relief(resolution, region, registration, use_srtm)\r\n    134             )\r\n    135         fname = which(f\"@earth_relief_{resolution}{reg}\", download=\"a\")\r\n--> 136         with xr.open_dataarray(fname) as dataarray:\r\n    137             grid = dataarray.load()\r\n    138             _ = grid.gmt  # load GMTDataArray accessor information\r\n\r\n~/.miniconda/envs/pygmt/lib/python3.9/site-packages/xarray/backends/api.py in open_dataarray(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)\r\n    657         )\r\n    658\r\n--> 659     dataset = open_dataset(\r\n    660         filename_or_obj,\r\n    661         decode_cf=decode_cf,\r\n\r\n~/.miniconda/envs/pygmt/lib/python3.9/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)\r\n    483\r\n    484     if engine is None:\r\n--> 485         engine = plugins.guess_engine(filename_or_obj)\r\n    486\r\n    487     backend = plugins.get_backend(engine)\r\n\r\n~/.miniconda/envs/pygmt/lib/python3.9/site-packages/xarray/backends/plugins.py in guess_engine(store_spec)\r\n    110             warnings.warn(f\"{engine!r} fails while guessing\", RuntimeWarning)\r\n    111\r\n--> 112     raise ValueError(\"cannot guess the engine, try passing one explicitly\")\r\n    113\r\n    114\r\n\r\nValueError: cannot guess the engine, try passing one explicitly\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.3.2.dev82+g82ebbbc4.d20210412\r\nSystem information:\r\n  python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]\r\n  executable: ~/.miniconda/envs/pygmt/bin/python\r\n  machine: macOS-11.2.3-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.20.1\r\n  pandas: 1.2.3\r\n  xarray: 0.18.0\r\n  netCDF4: 1.5.6\r\n  packaging: 20.9\r\n  ghostscript: 9.53.3\r\n  gmt: 6.1.1\r\n```\r\n",
    "closed_at": "2021-05-07T03:40:28Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "comments": 8,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "Using xarray directly gives the same error:\r\n```python\r\nimport xarray as xr\r\n# Fail with the same error\r\nxr.open_dataarray(\"~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\")\r\n# Specifying engine=\"netcdf4\" works\r\nxr.open_dataarray(\"~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\", engine=\"netcdf4\")\r\n```",
            "created_at": "2021-05-07T01:29:26Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-833992267",
            "id": 833992267,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzMzk5MjI2Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833992267/reactions"
            },
            "updated_at": "2021-05-07T01:29:26Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833992267",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Oops, a bit too slow, I'll close down #1263 as a duplicate.",
            "created_at": "2021-05-07T01:31:06Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-833992757",
            "id": 833992757,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzMzk5Mjc1Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 1,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833992757/reactions"
            },
            "updated_at": "2021-05-07T01:31:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833992757",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'm not familiar with xarray, but I guess that xarray tries to open the grid file using different engines, and it should work when it tries the \"netcdf4\" engine. It looks like an upstream bug to me, rather than a breaking API change.",
            "created_at": "2021-05-07T01:37:57Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-833994934",
            "id": 833994934,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzMzk5NDkzNA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833994934/reactions"
            },
            "updated_at": "2021-05-07T01:37:57Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833994934",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I'm not familiar with xarray, but I guess that xarray tries to open the grid file using different engines, and it should work when it tries the \"netcdf4\" engine. It looks like an upstream bug to me, rather than a breaking API change.\r\n\r\n`xarray` had a big backend engine refactor to handle multiple file formats (e.g. NetCDF, Zarr, etc) in a plugin-like way. I can try to raise an issue with upstream `xarray`, but they have a relatively slow release cycle (speaking from experience) and an xarray v0.18.1 probably won't come anytime soon in the next few weeks.\r\n\r\nI'm aware that this will cause issues for any PyGMT users creating a new environment with `xarray=0.18` and `pygmt=0.3.1` installed (at least those using the `load_earth_relief` function). So, we should probably fix this in PyGMT by explicitly setting the engine. I'm also wondering if this bugfix is critical enough to warrant a quick PyGMT v0.3.2 release.",
            "created_at": "2021-05-07T01:49:17Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-833998832",
            "id": 833998832,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzMzk5ODgzMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833998832/reactions"
            },
            "updated_at": "2021-05-07T01:49:17Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/833998832",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I can try to raise an issue with upstream `xarray`\r\n\r\nYes, please. \r\n\r\n> I'm also wondering if this bugfix is critical enough to warrant a quick PyGMT v0.3.2 release.\r\n\r\nYou mean creating a branch from the v0.3.1 tag, backport the changes in #1264, and make the v0.3.2 release? \r\n",
            "created_at": "2021-05-07T03:35:11Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-834038620",
            "id": 834038620,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzNDAzODYyMA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/834038620/reactions"
            },
            "updated_at": "2021-05-07T03:35:11Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/834038620",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> > I can try to raise an issue with upstream `xarray`\r\n> \r\n> Yes, please.\r\n\r\nIs a *.grd file the same as a NetCDF4 file? I've stepped through the `xarray` code and the easiest fix might be to update the line at https://github.com/pydata/xarray/blob/v0.18.0/xarray/backends/netCDF4_.py#L524), changing `ext in {\".nc\", \".nc4\", \".cdf\"}\r\n` to `ext in {\".nc\", \".nc4\", \".cdf\", \".grd\"}`, but I'm not sure if it's a good idea (afraid that it might break other libraries).\r\n\r\n> > I'm also wondering if this bugfix is critical enough to warrant a quick PyGMT v0.3.2 release.\r\n> \r\n> You mean creating a branch from the v0.3.1 tag, backport the changes in #1264, and make the v0.3.2 release?\r\n\r\nYes, that is one option (though not sure if I like that idea). Alternatively we can just start working on the PyGMT v0.4.0 release :see_no_evil:\r\n\r\nTechnically we've fixed this issue on the PyGMT side in #1264, but let's keep this issue pinned for a while, and keep watch to see if users make bug reports on the forum/github. If there's a lot of bug reports, maybe then go with a v0.3.2 release.",
            "created_at": "2021-05-07T04:02:32Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-834046924",
            "id": 834046924,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzNDA0NjkyNA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/834046924/reactions"
            },
            "updated_at": "2021-05-07T04:10:41Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/834046924",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Related upstream issue reports:\r\n\r\n- https://github.com/pydata/xarray/issues/5295\r\n- https://github.com/pydata/xarray/issues/5291",
            "created_at": "2021-05-17T01:52:00Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-841923994",
            "id": 841923994,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg0MTkyMzk5NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/841923994/reactions"
            },
            "updated_at": "2021-05-17T01:52:00Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/841923994",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "xarray v0.18.1 has been released (https://github.com/pydata/xarray/releases/tag/v0.18.1). The patch release should fix the problem.",
            "created_at": "2021-05-19T17:39:29Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262#issuecomment-844323546",
            "id": 844323546,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg0NDMyMzU0Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/844323546/reactions"
            },
            "updated_at": "2021-05-19T17:39:29Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/844323546",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262/comments",
    "created_at": "2021-05-07T01:26:48Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1262",
    "id": 878293537,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2021-06-21T14:49:45Z",
        "closed_issues": 244,
        "created_at": "2020-11-21T04:47:19Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": "2021-06-20T07:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/6",
        "id": 6133205,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/6/labels",
        "node_id": "MDk6TWlsZXN0b25lNjEzMzIwNQ==",
        "number": 6,
        "open_issues": 0,
        "state": "closed",
        "title": "0.4.0",
        "updated_at": "2021-11-03T23:29:33Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/6"
    },
    "node_id": "MDU6SXNzdWU4NzgyOTM1Mzc=",
    "number": 1262,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262/timeline",
    "title": "PyGMT load_earth_relief breaks with xarray 0.18.0 (ValueError: cannot guess the engine)",
    "updated_at": "2021-05-22T19:11:21Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1262",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    }
}