{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "COLLABORATOR",
    "body": "Fixes #361.\r\n\r\n## Description\r\n\r\nThe isssue was due to the fact that the returned values of `ner_report` were the result of a reduce operation (`.sum()` in this case) on a `pd.Series` of integers. And integers are represented by `np.int64` in `pandas`, rather than the native `int` type of Python.\r\n\r\nTwo possible solutions (see also [here](https://stackoverflow.com/questions/9452775/converting-numpy-dtypes-to-native-python-types)).\r\n1. Manually cast to desired type, e.g. `int(series.sum())`\r\n2. Extract the underlying value as a Python scalar with [`.item()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.item.html), e.g. `series.sum().item()`\r\n\r\nI think option 2 is better, since it's more generic: `np.float32` will be automatically converted to `float`, `np.int64` to `int` etc. So I used this approach.\r\n\r\n\r\n## How to test?\r\n\r\nThe test example given in #361 should now run without error.\r\n\r\n## Checklist\r\n\r\n- [x] This PR refers to an issue from the [issue tracker](https://github.com/BlueBrain/Search/issues).\r\n  (if it is not the case, please create an issue first).\r\n- [ ] All CI tests pass. \r\n",
    "closed_at": "2021-05-07T13:20:03Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/17013890?v=4",
        "events_url": "https://api.github.com/users/FrancescoCasalegno/events{/privacy}",
        "followers_url": "https://api.github.com/users/FrancescoCasalegno/followers",
        "following_url": "https://api.github.com/users/FrancescoCasalegno/following{/other_user}",
        "gists_url": "https://api.github.com/users/FrancescoCasalegno/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/FrancescoCasalegno",
        "id": 17013890,
        "login": "FrancescoCasalegno",
        "node_id": "MDQ6VXNlcjE3MDEzODkw",
        "organizations_url": "https://api.github.com/users/FrancescoCasalegno/orgs",
        "received_events_url": "https://api.github.com/users/FrancescoCasalegno/received_events",
        "repos_url": "https://api.github.com/users/FrancescoCasalegno/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/FrancescoCasalegno/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/FrancescoCasalegno/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/FrancescoCasalegno"
    },
    "comments": 0,
    "comments_content": [],
    "comments_url": "https://api.github.com/repos/BlueBrain/Search/issues/362/comments",
    "created_at": "2021-05-07T11:22:44Z",
    "draft": false,
    "events_url": "https://api.github.com/repos/BlueBrain/Search/issues/362/events",
    "html_url": "https://github.com/BlueBrain/Search/pull/362",
    "id": 878813660,
    "labels": [
        {
            "color": "d73a4a",
            "default": false,
            "description": "Something isn't working",
            "id": 1938483675,
            "name": "\ud83d\udc1b bug fix",
            "node_id": "MDU6TGFiZWwxOTM4NDgzNjc1",
            "url": "https://api.github.com/repos/BlueBrain/Search/labels/%F0%9F%90%9B%20bug%20fix"
        }
    ],
    "labels_url": "https://api.github.com/repos/BlueBrain/Search/issues/362/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NjMyNTg5MjU0",
    "number": 362,
    "performed_via_github_app": null,
    "pull_request": {
        "diff_url": "https://github.com/BlueBrain/Search/pull/362.diff",
        "html_url": "https://github.com/BlueBrain/Search/pull/362",
        "merged_at": "2021-05-07T13:20:02Z",
        "patch_url": "https://github.com/BlueBrain/Search/pull/362.patch",
        "url": "https://api.github.com/repos/BlueBrain/Search/pulls/362"
    },
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/BlueBrain/Search/issues/362/reactions"
    },
    "repository_url": "https://api.github.com/repos/BlueBrain/Search",
    "state": "closed",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/BlueBrain/Search/issues/362/timeline",
    "title": "Fix NER eval bug \u2014 dtype conversion from NumPy's to Python's",
    "updated_at": "2021-05-07T13:20:07Z",
    "url": "https://api.github.com/repos/BlueBrain/Search/issues/362",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/17013890?v=4",
        "events_url": "https://api.github.com/users/FrancescoCasalegno/events{/privacy}",
        "followers_url": "https://api.github.com/users/FrancescoCasalegno/followers",
        "following_url": "https://api.github.com/users/FrancescoCasalegno/following{/other_user}",
        "gists_url": "https://api.github.com/users/FrancescoCasalegno/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/FrancescoCasalegno",
        "id": 17013890,
        "login": "FrancescoCasalegno",
        "node_id": "MDQ6VXNlcjE3MDEzODkw",
        "organizations_url": "https://api.github.com/users/FrancescoCasalegno/orgs",
        "received_events_url": "https://api.github.com/users/FrancescoCasalegno/received_events",
        "repos_url": "https://api.github.com/users/FrancescoCasalegno/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/FrancescoCasalegno/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/FrancescoCasalegno/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/FrancescoCasalegno"
    }
}